import type { PortalContent } from "./types";

/** ترجمات المنصة — العربية (المصدر) */
export const portalAr: PortalContent = {
  auth: {
    loginTitle: "تسجيل الدخول",
    loginSubtitle: "أدخل بياناتك للوصول إلى حسابك",
    loginButton: "دخول",
    logout: "تسجيل الخروج",
    registerTitle: "إنشاء حساب",
    registerSubtitle: "حساب عميل جديد — للطاقم تُستخدم الدعوات",
    registerButton: "إنشاء الحساب",
    registerSuccessTitle: "أُنشئ حسابك",
    registerSuccessBody: "أرسلنا رابط تأكيد إلى بريدك الإلكتروني. أكّده لتفعيل الحساب وبدء تقديم الطلبات.",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    passwordHint: "8 محارف فأكثر، حروف وأرقام",
    currentPassword: "كلمة المرور الحالية",
    newPassword: "كلمة المرور الجديدة",
    confirmPassword: "تأكيد كلمة المرور",
    forgotTitle: "استعادة كلمة المرور",
    forgotHint: "أدخل بريدك وسنرسل رابط إعادة التعيين إن وُجد حساب مرتبط به.",
    forgotButton: "إرسال رابط الاستعادة",
    forgotSent: "إن كان البريد مسجلًا فستصلك رسالة خلال دقائق.",
    forgotSentDev: "وضع التطوير: الرابط أدناه (لن يظهر في الإنتاج).",
    resetTitle: "كلمة مرور جديدة",
    resetButton: "ضبط كلمة المرور",
    resetSuccess: "غُيّرت كلمة المرور — سجّل الدخول من جديد.",
    verifyTitle: "تأكيد البريد الإلكتروني",
    verifyOk: "تم تأكيد بريدك",
    verifyOkBody: "حسابك مفعّل الآن. سجّل الدخول لبدء استخدام بوابة العميل.",
    verifyAlready: "كان بريدك مؤكدًا مسبقًا",
    verifyInvalid: "رابط غير صالح",
    verifyInvalidBody: "انتهت صلاحية الرابط أو استُخدم من قبل. اطلب رابطًا جديدًا من صفحة الدخول.",
    noAccount: "ليس لديك حساب؟",
    haveAccount: "لديك حساب بالفعل؟",
    backHome: "العودة للموقع",
    pendingVerification: "بريدك غير مؤكد بعد",
    pendingVerificationBody: "تأكيد البريد يفعّل إرسال الطلبات والمحادثات. راجع بريدك أو أعد إرسال رابط التأكيد.",
    resendVerification: "إعادة إرسال رابط التأكيد",
    devOutboxHint: "وضع تطوير البريد: الرسائل تُسجل في صندوق الصادر داخل لوحة الإدارة ولا تُرسل فعليًا.",
    errors: {
      invalid: "بيانات غير صالحة",
      wrongPassword: "كلمة المرور الحالية غير صحيحة",
      emailTaken: "البريد مستخدم في حساب آخر",
      rateLimited: "محاولات كثيرة — انتظر قليلًا ثم أعد المحاولة",
      credentials: "تعذّر تسجيل الدخول — تحقق من البريد وكلمة المرور (أو أن الحساب غير متاح)",
      locked: "قُفل الحساب مؤقتًا بسبب محاولات دخول فاشلة متكررة",
      passwordWeak: "كلمة المرور ضعيفة: 8 محارف فأكثر مع حروف وأرقام",
      passwordMismatch: "كلمتا المرور غير متطابقتين",
      nameInvalid: "الاسم غير صالح",
      emailInvalid: "البريد الإلكتروني غير صالح",
      required: "هذا الحقل مطلوب",
      generic: "حدث خطأ غير متوقع — أعد المحاولة",
    },
  },
  track: {
    title: "متابعة البطاقة",
    invalid: "الرابط غير صالح",
    invalidBody: "تأكد من الرابط كما وصل إليك تمامًا، أو تواصل معنا لإصدار رابط جديد.",
    expired: "انتهت صلاحية الرابط",
    expiredBody: "انتهت مدة صلاحية رابط المتابعة — تواصل معنا لإصدار رابط جديد لبطاقتك.",
    revoked: "أُلغي هذا الرابط",
    revokedBody: "أوقف صاحب الصلاحية رابط المتابعة هذا. لا تقلق — بيانات البطاقة نفسها محفوظة ويمكن الوصول إليها بالطرق المعتمدة.",
    loginRequired: "الاطلاع يتطلب تسجيل الدخول",
    loginRequiredBody: "سياسة هذه البطاقة تتيح المتابعة عبر الحساب المخوّل فقط.",
    signIn: "تسجيل الدخول",
    closed: "البطاقة مغلقة",
    closedBody: "لا يمكن إضافة ردود جديدة على بطاقة مغلقة — يمكنك مراجعة المحادثة السابقة.",
    rateLimited: "محاولات كثيرة — انتظر قليلًا ثم أعد المحاولة",
    cardType: { request: "طلب مشروع", inquiry: "استفسار" },
    refLabel: "الرقم المرجعي",
    status: "الحالة",
    created: "أُنشئت",
    lastUpdate: "آخر تحديث",
    timeline: "تسلسل الحالة",
    conversation: "الردود",
    noReplies: "لا ردود بعد",
    guestAuthor: "صاحب رابط المتابعة",
    ownerAuthor: "صاحب البطاقة",
    staffAuthor: "فريق سُحُب التقنية",
    you: "أنت",
    replyTitle: "أضف ردًا",
    replyPlaceholder: "اكتب ردك هنا…",
    replyDisabledView: "هذه البطاقة تتيح الاطلاع فقط عبر الرابط",
    replyDisabledLogin: "الرد متاح لحساب مخوّل فقط — سجّل الدخول للمتابعة",
    replyDisabledClosed: "الردود مغلقة على هذه البطاقة",
    send: "إرسال الرد",
    sending: "جارٍ الإرسال…",
    replySent: "أُرسل ردك بنجاح",
    replyFailed: "تعذر إرسال الرد — أعد المحاولة",
    replyDuplicate: "رد مطابق أُرسل قبل لحظات",
    copyLink: "نسخ الرابط",
    copied: "نُسخ الرابط",
    attachments: "مرفقات",
    backHome: "العودة إلى الرئيسية",
    statusLabels: {
      new: "جديد",
      in_review: "قيد المراجعة",
      awaiting_info: "بانتظار معلومات",
      in_progress: "قيد التنفيذ",
      responded: "تم الرد",
      closed: "مغلقة",
      cancelled: "ملغاة",
    },
    openTracking: "فتح المتابعة",
    copyTracking: "نسخ الرابط",
    trackingHint: "احفظ هذا الرابط لمتابعة بطاقتك والرد عليها في أي وقت — يعمل دون حساب وفق سياسة الوصول.",
    trackingUnavailable: "تعذر إنشاء رابط المتابعة الآن — احتفظ برقمك المرجعي ويمكن إصدار رابط لاحقًا.",
  },
  account: {
    nav: {
      dashboard: "اللوحة",
      requests: "طلباتي",
      newRequest: "طلب جديد",
      inquiries: "الاستفسارات",
      notifications: "الإشعارات",
      profile: "الملف الشخصي",
      security: "الأمان والجلسات",
      logout: "تسجيل الخروج",
      backSite: "الموقع العام",
    },
    dashboard: {
      title: "لوحة حسابك",
      welcome: "مرحبًا",
      welcomeWithName: "مرحبًا، {name}",
      openRequests: "طلبات مفتوحة",
      awaitingReply: "بانتظار ردك",
      unreadNotifications: "إشعارات غير مقروءة",
      totalRequests: "إجمالي الطلبات",
      openInquiries: "استفسارات مفتوحة",
      totalInquiries: "إجمالي الاستفسارات",
      recentUpdates: "آخر التحديثات",
      emptyTitle: "لا طلبات بعد",
      emptyBody: "أنشئ طلبك الأول — ناقش فكرتك أو اطلب عرض سعر.",
      createRequest: "إنشاء طلب",
      viewAll: "عرض الكل",
    },
    requests: {
      title: "طلباتي",
      subtitle: "تابع حالة طلباتك ومحادثاتها",
      create: "طلب جديد",
      refCode: "الرقم المرجعي",
      status: "الحالة",
      service: "الخدمة",
      created: "تاريخ الإنشاء",
      lastActivity: "آخر نشاط",
      empty: "لا طلبات بعد",
      emptyBody: "ابدأ بإنشاء طلب جديد وسيظهر هنا مع محادثته.",
      viewDetails: "عرض التفاصيل",
      cancelEdit: "إلغاء",
      submitSuccess: "أُرسل طلبك",
      submitSuccessBody: "رقمه المرجعي أدناه — سيتواصل معك الفريق قريبًا.",
      claimTitle: "ربط طلب سابق",
      claimBody: "أدخل الرقم المرجعي لطلب قدمته قبل إنشاء الحساب، وسنرسل رابط تأكيد لربطه بحسابك.",
      claimButton: "إرسال رابط الربط",
      claimSent: "إن كان الطلب موجودًا فستصلك رسالة تأكيد الربط.",
      claimVerifyTitle: "ربط الطلب بحسابك",
      claimVerifyOk: "رُبط الطلب بحسابك بنجاح",
      statuses: {
        new: "جديد",
        in_review: "قيد المراجعة",
        awaiting_info: "بانتظار معلومات",
        in_progress: "قيد المعالجة",
        responded: "تم الرد",
        closed: "مغلق",
        cancelled: "ملغى",
      },
      services: {
        web: "تطوير الويب",
        mobile: "تطبيقات الجوال",
        systems: "الأنظمة الإدارية",
        ux: "تجربة المستخدم",
        automation: "الأتمتة والتكامل",
        maintenance: "الصيانة والدعم",
        unsure: "غير محدد",
      },
      draftRestored: "استُعدت مسودة طلبك السابقة",
      draftSaved: "حُفظت المسودة",
      draftCleared: "مُسحت المسودة",
      search: "بحث",
      searchPlaceholder: "ابحث بالرقم المرجعي أو الخدمة أو الحالة…",
      noResults: "لا نتائج مطابقة لبحثك",
      clearSearch: "مسح البحث",
      awaitingYou: "بانتظار ردك",
      awaitingHours: "{n} ساعة",
      awaitingDays: "{n} يوم",
    },
    detail: {
      conversation: "المحادثة",
      openTracking: "فتح بطاقة المتابعة",
      internalHidden: "الملاحظات الداخلية للفريق لا تظهر هنا",
      replyPlaceholder: "اكتب ردك أو إضافتك…",
      send: "إرسال",
      sending: "جارٍ الإرسال…",
      attachFile: "إرفاق ملف",
      attachments: "المرفقات",
      download: "تنزيل",
      history: "السجل",
      statusTimeline: "مسار الحالة",
      assignedTo: "المسؤول",
      unassigned: "غير معيّن",
      closedNote: "سبب الإغلاق",
      replySuccess: "أُرسل ردك",
      replyEmpty: "اكتب نص الرسالة أولًا",
      fileTooLarge: "الملف أكبر من الحد المسموح",
      fileTypeInvalid: "نوع الملف غير مسموح",
      you: "أنت",
      staff: "الفريق",
      system: "النظام",
      noMessages: "لا رسائل بعد — الفريق سيرد قريبًا",
      requestInfo: "بيانات الطلب",
      priority: "الأولوية",
      timeline: "الإطار الزمني",
      budget: "الميزانية",
      currency: "العملة",
      contactPref: "قناة التواصل المفضلة",
      reference: "رابط مرجعي",
      print: "طباعة الطلب",
    },
    inquiries: {
      title: "استفساراتي",
      subtitle: "أسئلة سريعة وأجوبة فريق سُحُب في محادثة واحدة",
      create: "استفسار جديد",
      refCode: "الرقم المرجعي",
      subject: "الموضوع",
      category: "التصنيف",
      categories: {
        general: "عام",
        services: "الخدمات",
        pricing: "الأسعار",
        support: "الدعم",
        other: "أخرى",
      },
      status: "الحالة",
      statuses: {
        new: "جديد",
        in_review: "قيد المراجعة",
        awaiting_info: "بانتظار معلومات",
        responded: "تم الرد",
        closed: "مغلق",
      },
      all: "عرض الكل",
      openShortcut: "استفسارات مفتوحة",
      messages: "الرسائل",
      created: "تاريخ الإنشاء",
      lastActivity: "آخر نشاط",
      empty: "لا استفسارات بعد",
      emptyBody: "اطرح سؤالك القصير هنا وسيرد الفريق في نفس المحادثة.",
      noResults: "لا نتائج مطابقة لبحثك",
      viewDetails: "عرض المحادثة",
      back: "كل الاستفسارات",
      notFound: "الاستفسار غير موجود أو لا تملك صلاحية عرضه",
      conversation: "المحادثة",
      meta: "تفاصيل الاستفسار",
      assignedTo: "المسؤول",
      unassigned: "غير معيَّن بعد",
      you: "أنت",
      team: "فريق سُحُب",
      system: "النظام",
      noMessages: "لا رسائل بعد",
      statusTimeline: "سجل الحالة",
      replyPlaceholder: "اكتب ردك أو استفسارك الإضافي…",
      send: "إرسال",
      sending: "يُرسل…",
      replySuccess: "أُرسل ردك",
      replyEmpty: "اكتب نص الرسالة أولًا",
      closedNote: "هذا الاستفسار مغلق — ابدأ استفسارًا جديدًا إن احتجت مساعدة إضافية.",
      formTitle: "استفسار جديد",
      formIntro: "سؤال قصير؟ اكتبه هنا وسيتولى الفريق الرد في محادثة خاصة.",
      formSubject: "الموضوع",
      formSubjectPlaceholder: "مثال: هل تقدمون صيانة شهرية؟",
      formCategory: "التصنيف",
      formMessage: "سؤالك",
      formMessagePlaceholder: "اكتب سؤالك بوضوح — التفاصيل تساعدنا على رد أدق.",
      formSubmit: "إرسال الاستفسار",
      formCancel: "إلغاء",
      createdOk: "أُرسل استفسارك",
      createdOkBody: "رقمه المرجعي أدناه — سيرد الفريق قريبًا.",
      createdOkOpen: "متابعة المحادثة",
      attachments: "المرفقات",
      download: "تنزيل",
      print: "طباعة الاستفسار",
    openTracking: "فتح بطاقة المتابعة",
    },
    notifications: {
      title: "الإشعارات",
      markRead: "تعليم كمقروء",
      markAllRead: "تعليم الكل كمقروء",
      empty: "لا إشعارات",
      types: {
        new_request: "طلب جديد",
        new_inquiry: "استفسار جديد",
        request_assigned: "تعيين طلب",
        reply_received: "رد جديد",
        info_requested: "طلب معلومات",
        status_changed: "تغيير حالة",
        content_published: "نشر محتوى",
        content_schedule: "جدولة النشر",
        account: "الحساب",
      },
    },
    profile: {
      title: "الملف الشخصي",
      name: "الاسم",
      phone: "الهاتف",
      company: "الشركة",
      language: "لغة الواجهة المفضلة",
      save: "حفظ التغييرات",
      saved: "حُفظت التغييرات",
      emailReadonly: "البريد الإلكتروني لا يُغير من هنا — تواصل مع الدعم",
      verified: "بريد مؤكد",
      notVerified: "بريد غير مؤكد",
    },
    security: {
      title: "الأمان والجلسات",
      changePassword: "تغيير كلمة المرور",
      passwordChanged: "غُيّرت كلمة المرور",
      passwordChangedBody: "أُبطلت كل الجلسات — سجّل الدخول من جديد.",
      sessions: "الجلسات النشطة",
      currentSession: "هذا الجهاز",
      thisDevice: "هذا الجهاز",
      revoke: "إبطال",
      revokeAll: "إبطال البقية",
      revoked: "أُبطلت الجلسة",
      lastActive: "آخر ظهور",
      created: "أُنشئت",
      unknownDevice: "جهاز غير معروف",
      noSessions: "لا جلسات نشطة أخرى",
      relogin: "سجّل الدخول من جديد",
    },
  },
  admin: {
    track: {
      section: "رابط المتابعة",
      noLink: "لا يوجد رابط متابعة لهذه البطاقة",
      stateValid: "فعّال",
      stateExpired: "منتهي",
      stateRevoked: "ملغى",
      expiresAt: "ينتهي في",
      revokedAt: "أُلغي في",
      renew: "تجديد الرابط",
      renewed: "جُدد الرابط — انسخه الآن وأرسله للعميل (لا يُعرض مجددًا)",
      renewHint: "التجديد يُصدر رمزًا جديدًا ويبطل الرمز السابق — ويُرسل رمزًا بديلًا ببريد البطاقة (وضع التطوير: صندوق الصادر)",
      renewEmailedTo: "وصلت نسخة بالبريد إلى",
      revoke: "إلغاء الرابط",
      revokeConfirm: "سيفقد حامل الرابط وصوله فورًا. متابعة؟",
      revoked: "أُلغي رابط المتابعة",
      effectivePolicy: "السياسة الفعلية لهذه البطاقة",
      policySource: {
        platform_force_login: "فرض تسجيل الدخول (إعداد المنصة)",
        card_exception: "استثناء خاص بهذه البطاقة",
        type_default: "الإعداد الافتراضي لنوع البطاقة",
      },
      mode: {
        login_required: "تسجيل الدخول مطلوب",
        link_view: "متابعة بالرابط — اطلاع فقط",
        link_reply: "متابعة بالرابط — اطلاع ورد",
        link_view_login_reply: "عرض بالرابط — الرد بحساب",
      },
      forceLoginActive: "«فرض تسجيل الدخول» مفعّل على مستوى المنصة ويتغلب على أي استثناء",
    },
    nav: {
      dashboard: "اللوحة",
      users: "المستخدمون",
      requests: "الطلبات",
      inquiries: "الاستفسارات",
      notifications: "الإشعارات",
      pages: "الصفحات",
      media: "الوسائط",
      menus: "القوائم",
      settings: "الإعدادات",
      audit: "سجل التدقيق",
      outbox: "صندوق الصادر",
      backSite: "الموقع العام",
      logout: "تسجيل الخروج",
    },
    search: {
      trigger: "بحث شامل",
      placeholder: "ابحث في المستخدمين والطلبات والاستفسارات والصفحات…",
      quickNav: "تنقل سريع",
      results: "النتائج",
      searching: "جارٍ البحث…",
      noResults: "لا نتائج مطابقة لبحثك",
      noResultsHint: "جرّب كلمة مختلفة أو رقم مرجع (مثل S7-)",
      openHint: "افتح لعرض النتيجة",
    },
    dashboard: {
      title: "لوحة الإدارة",
      totalUsers: "إجمالي المستخدمين",
      activeUsers: "حسابات نشطة",
      pendingUsers: "بانتظار التحقق",
      openRequests: "طلبات مفتوحة",
      newRequests: "طلبات جديدة",
      awaitingInfo: "بانتظار معلومات",
      unansweredRequests: "طلبات بلا رد",
      openInquiries: "استفسارات مفتوحة",
      publishedPages: "صفحات منشورة",
      draftPages: "مسودات صفحات",
      requestsByStatus: "الطلبات حسب الحالة",
      recentActivity: "أحدث الأحداث",
      recentRequests: "أحدث الطلبات",
      viewAll: "عرض الكل",
      noData: "لا بيانات بعد",
      last7days: "آخر 7 أيام",
      rangeLabel: "اختيار المدى الزمني",
      range7: "آخر 7 أيام",
      range30: "آخر 30 يومًا",
      range90: "آخر 90 يومًا",
      overdueReplies: "ردود متأخرة",
      overdueHint: "بانتظار رد الفريق أكثر من 24 ساعة",
    },
    users: {
      title: "المستخدمون",
      subtitle: "إدارة الحسابات والأدوار والحالات",
      search: "بحث",
      searchPlaceholder: "اسم أو بريد…",
      role: "الدور",
      status: "الحالة",
      statusActive: "نشط",
      statusPending: "بانتظار التحقق",
      statusSuspended: "موقوف",
      createdAt: "الإنشاء",
      lastLogin: "آخر دخول",
      requests: "الطلبات",
      actions: "إجراءات",
      suspend: "إيقاف",
      activate: "تفعيل",
      changeRole: "تغيير الدور",
      invite: "دعوة",
      inviteTitle: "دعوة مستخدم",
      inviteEmail: "بريد المدعو",
      inviteRole: "الدور الممنوح",
      inviteSend: "إرسال الدعوة",
      inviteSent: "أُرسلت الدعوة",
      edit: "تعديل",
      save: "حفظ",
      saved: "حُفظ",
      cancel: "إلغاء",
      confirmSuspend: "إيقاف هذا الحساب؟ ستُبطل جلساته فورًا.",
      confirmActivate: "إعادة تفعيل هذا الحساب؟",
      confirmLastAdmin: "لا يمكن إيقاف أو تخفيض آخر مدير نظام نشط.",
      emailVerified: "بريد مؤكد",
      notVerified: "بريد غير مؤكد",
      never: "لم يسجل دخولًا",
      filterAll: "الكل",
      userUpdated: "حُدّث المستخدم",
      lastAdminError: "الإجراء مرفوض: آخر مدير نظام نشط",
      sendReset: "إرسال استعادة كلمة المرور",
      resetSent: "أُرسل رابط الاستعادة",
      viewProfile: "عرض الملف",
      detail: {
        title: "ملف المستخدم",
        back: "عودة إلى المستخدمين",
        accountInfo: "بيانات الحساب",
        totalRequests: "إجمالي الطلبات",
        openRequests: "طلبات مفتوحة",
        userRequests: "طلبات المستخدم",
        activityLog: "آخر الأنشطة",
        sessionsCount: "الجلسات النشطة",
        noRequests: "لا طلبات لهذا المستخدم بعد",
        suspendedAt: "تاريخ الإيقاف",
        lastSeen: "آخر ظهور",
      },
    },
    requests: {
      title: "الطلبات",
      subtitle: "متابعة العملاء والرد وتوزيع العمل",
      searchPlaceholder: "رقم مرجعي، بريد، اسم، نص…",
      filterStatus: "الحالة",
      filterPriority: "الأولوية",
      filterService: "الخدمة",
      filterAssignee: "المسؤول",
      filterOverdue: "متأخر الرد +24 ساعة",
      filterAll: "الكل",
      unassigned: "غير معيّن",
      assign: "تعيين",
      assignTo: "تعيين إلى",
      assignToMe: "تعيين لي",
      changeStatus: "تغيير الحالة",
      reply: "رد على العميل",
      internalNote: "ملاحظة داخلية",
      internalNoteHint: "تظهر للطاقم فقط — لا تصل للعميل",
      archive: "أرشفة",
      restore: "استعادة",
      archived: "مؤرشف",
      clientReply: "رد العميل",
      staffReply: "رد الطاقم",
      client: "العميل",
      none: "—",
      lastActivity: "آخر نشاط",
      viewDetails: "التفاصيل",
      bulkArchive: "أرشفة المحدد",
      selected: "محدد",
      priority: "الأولوية",
      requestType: "نوع الطلب",
      discussion: "نقاش",
      quote: "عرض سعر",
      statuses: {
        new: "جديد",
        in_review: "قيد المراجعة",
        awaiting_info: "بانتظار معلومات",
        in_progress: "قيد المعالجة",
        responded: "تم الرد",
        closed: "مغلق",
        cancelled: "ملغى",
      },
      priorities: {
        low: "منخفضة",
        normal: "عادية",
        high: "عالية",
        urgent: "عاجلة",
      },
      services: {
        web: "الويب",
        mobile: "الجوال",
        systems: "الأنظمة",
        ux: "تجربة المستخدم",
        automation: "الأتمتة",
        maintenance: "الصيانة",
        unsure: "غير محدد",
      },
      budget: "الميزانية",
      currency: "العملة",
      timelinePref: "الإطار الزمني",
      contactPref: "قناة التواصل",
      contact: "التواصل",
      reference: "مرجع",
      history: "السجل",
      conversation: "المحادثة",
      messages: "رسائل",
      empty: "لا طلبات مطابقة",
      emptyBody: "عدّل عوامل التصفية أو انتظر وصول طلبات جديدة.",
      closeReason: "سبب الإغلاق/الإلغاء",
      closeReasonPlaceholder: "سبب يظهر للعميل…",
      statusNotePlaceholder: "ملاحظة على تغيير الحالة (اختياري)…",
      applyStatus: "تطبيق",
      sentReply: "أُرسل الرد",
      sentNote: "أُضيفت الملاحظة الداخلية",
      clientView: "معاينة ما يراه العميل",
      export: "تصدير CSV",
      exportOk: "ملف CSV جاهز؛ طُلب بدء التنزيل",
      exportLimit: "تجاوز التصدير 100,000 صف أو 32 MiB. ضيّق المرشحات وحاول مجددًا.",
      exportFailed: "تعذر تجهيز التنزيل. تحقق من الجلسة والصلاحيات ثم أعد المحاولة.",
      awaitingTeam: "بانتظار رد الفريق",
      overdueReply: "رد متأخر",
      agingHours: "{n} ساعة",
      agingDays: "{n} يوم",
      presetSave: "حفظ التصفية",
      presetName: "اسم التصفية",
      presetSaved: "حُفظت التصفية",
      presetRemoved: "حُذفت التصفية",
      presetApply: "تطبيق التصفية المحفوظة",
      presetDelete: "حذف التصفية المحفوظة",
      print: "طباعة الطلب",
    },
    inquiries: {
      title: "الاستفسارات",
      subtitle: "أسئلة عامة وتواصل مباشر",
      subject: "الموضوع",
      category: "التصنيف",
      categories: {
        general: "عام",
        services: "الخدمات",
        pricing: "الأسعار",
        support: "الدعم",
        other: "أخرى",
      },
      new: "جديد",
      reply: "رد",
      assign: "تعيين",
      conversation: "المحادثة",
      empty: "لا استفسارات",
      statuses: {
        new: "جديد",
        in_review: "قيد المراجعة",
        awaiting_info: "بانتظار معلومات",
        responded: "تم الرد",
        closed: "مغلق",
      },
      export: "تصدير CSV",
      exportOk: "ملف CSV جاهز؛ طُلب بدء التنزيل",
      exportLimit: "تجاوز التصدير 100,000 صف أو 32 MiB. ضيّق المرشحات وحاول مجددًا.",
      exportFailed: "تعذر تجهيز التنزيل. تحقق من الجلسة والصلاحيات ثم أعد المحاولة.",
      archive: "أرشفة",
      restore: "استعادة",
      archived: "مؤرشف",
      bulkArchive: "أرشفة المحدد",
      selected: "محدد",
      print: "طباعة الاستفسار",
    },
    notifications: {
      title: "الإشعارات",
      subtitle: "تحديثات الطلبات والاستفسارات والمحتوى الموجهة للفريق",
      markRead: "تعليم كمقروء",
      markAllRead: "تعليم الكل كمقروء",
      empty: "لا إشعارات",
      types: {
        new_request: "طلب جديد",
        new_inquiry: "استفسار جديد",
        request_assigned: "تعيين طلب",
        reply_received: "رد جديد",
        info_requested: "طلب معلومات",
        status_changed: "تغيير حالة",
        content_published: "نشر محتوى",
        content_schedule: "جدولة النشر",
        account: "الحساب",
      },
    },
    pages: {
      title: "الصفحات",
      subtitle: "محتوى الموقع — تحرير ونشر وإصدارات",
      createPage: "صفحة جديدة",
      pageTitle: "الصفحة",
      rowActions: "إجراءات — {title}",
      slug: "المسار",
      slugHint: "أحرف لاتينية صغيرة وأرقام وشرطات — يترك فارغًا للرئيسية فقط",
      status: "الحالة",
      order: "الترتيب",
      updated: "آخر تحديث",
      edit: "تحرير",
      duplicate: "نسخ",
      archive: "أرشفة",
      restore: "استعادة",
      preview: "معاينة",
      published: "منشورة",
      draft: "مسودة",
      inReview: "قيد المراجعة",
      archivedStatus: "مؤرشفة",
      visibility: "الظهور",
      visibilityPublic: "عامة",
      visibilityAuth: "للمسجلين",
      visibilityRole: "لأدوار محددة",
      home: "الرئيسية",
      setHome: "تعيين كرئيسية",
      notHome: "ليست الرئيسية",
      newPageTitle: "صفحة جديدة",
      empty: "لا صفحات",
      emptyBody: "أنشئ أول صفحة من زر «صفحة جديدة».",
      versions: "الإصدارات",
      scheduledFor: "مجدولة للنشر · {time}",
      versionHistory: "تاريخ الإصدارات",
      restoreVersion: "استعادة هذا الإصدار",
      currentVersion: "الإصدار الحالي",
      compare: "مقارنة",
      editorTouched: "عدّلها محرر — البذرة لن تلمسها",
      restoreBoth: "استعادة اللغتين معًا",
      restoreThisLocale: "استعادة هذه اللغة",
      versionNotFound: "الإصدار غير موجود لهذه اللغة",
      slugTaken: "هذا المسار مستخدم بصفحة أخرى",
      slugInvalid: "صيغة المسار غير صالحة",
      homeSlugHint: "الرئيسية تُخدم من المسار الفارغ (/) — لا يمكن تغييره",
    },
    editor: {
      title: "محرر الصفحة",
      saved: "محفوظة",
      saving: "جارٍ الحفظ…",
      saveFailed: "فشل الحفظ — أعد المحاولة",
      unsaved: "تغييرات غير محفوظة",
      publish: "نشر",
      publishDisabled: "النشر بصلاحية مستقلة",
      publishedOk: "نُشرت الصفحة",
      ar: "العربية",
      en: "الإنجليزية",
      blocks: "الكتل",
      library: "المكتبة",
      layers: "الطبقات",
      searchLayers: "ابحث في الطبقات…",
      canvas: "المعاينة",
      properties: "الخصائص",
      addChild: "إضافة عنصر داخل",
      emptyContainer: "أضف عنصرًا",
      containerFull: "الحاوية ممتلئة — الحد الأقصى {max} عنصرًا",
      nodeLimit: "بلغت الحد الأقصى لعدد عناصر الصفحة",
      nodeDeleted: "حُذف العنصر — يمكنك التراجع",
      selectType: "اختر النوع",
      appearance: "المظهر حسب الجهاز",
      deviceBase: "الأساس",
      inherited: "موروث من الأساس",
      reset: "إعادة الضبط",
      presets: "أنماط جاهزة",
      presetScopeNote: "النمط يُطبّق على هذه العقدة فقط",
      iframePreview: "معاينة iframe",
      previewWidth: "عرض المعاينة",
      previewZoom: "التكبير",
      refreshPreview: "تحديث المعاينة",
      previewSavedNote: "تُظهر المعاينة آخر مسودة محفوظة",
      testMode: "وضع الاختبار",
      testModeBanner: "وضع اختبار التفاعل — الإرسال محاكى ولا تُرسل طلبات حقيقية",
      confirmDeleteTree: "سيُحذف هذا العنصر مع {count} عنصر داخله.",
      pageRoot: "الصفحة",
      maxDepthHint: "أقصى عمق للشجرة",
      addBlock: "إضافة",
      insertHere: "أدرج هنا",
      delete: "حذف",
      duplicate: "تكرار",
      copyToClipboard: "نسخ إلى الحافظة",
      copiedToClipboard: "نُسخ إلى الحافظة — الصقه في أي صفحة",
      paste: "لصق",
      pasteFromClipboard: "لصق من الحافظة",
      pastedFromClipboard: "تم اللصق — يمكنك التراجع",
      clipboardEmpty: "الحافظة فارغة — انسخ عنصرًا من أي صفحة أولًا",
      clipboardCleared: "أُفرغت الحافظة",
      clearClipboard: "إفراغ الحافظة",
      pasteNotAllowedHere: "هذا النوع لا يُلصق داخل هذا الأب — جرّب مستوى أعلى",
      layerDragHandle: "مقبض سحب",
      dropIntoContainer: "أفلت هنا لإضافة الكتلة داخل هذه الحاوية",
      moveIntoOwnChild: "لا يمكن نقل الكتلة داخل أحد أبنائها",
      moveNotAllowedHere: "لا يمكن إسقاط هذا النوع هنا — الحاوية الهدف لا تقبله",
      moveUp: "أعلى",
      moveDown: "أسفل",
      undo: "تراجع",
      redo: "إعادة",
      preview: "معاينة",
      deviceDesktop: "كمبيوتر",
      deviceTablet: "تابلت",
      deviceMobile: "جوال",
      quickAdd: "إضافة سريعة لكتلة",
      searchBlocks: "ابحث في الكتل بالاسم…",
      noBlocks: "لا كتل مطابقة لبحثك",
      selectedBlock: "العنصر المحدد",
      inlineEdit: "تحرير النص مباشرة",
      inlineEditHint: "انقر نقرًا مزدوجًا للتحرير المباشر داخل الرسم",
      inlineEditingBadge: "تحرير مباشر — Enter للالتزام وEsc للإلغاء",
      editorGuide: {
        title: "دليل المحرر",
        description: "كل ما تحتاجه لإتقان محرر الصفحات — من أول كتلة حتى نشر مجدول.",
        filterPlaceholder: "ابحث في الدليل…",
        noResults: "لا نتائج مطابقة — جرّب كلمة أخرى",
        openHint: "F1 أو ؟ من أي مكان في المحرر",
        sections: [
          {
            title: "نظرة عامة على المحرر",
            body: [
              "الشريط العلوي يجمع لغة المسودة، مؤشر الحفظ، التراجع/الإعادة، أجهزة المعاينة (375/768/1280)، الإصدارات، القوالب، الجدولة والنشر.",
              "الرسم يعرض المحتوى كما سيراه الزوار تمامًا، وعلى جانبيه المكتبة وخصائص الكتلة المحددة (تتبدل مواضعها مع اتجاه اللغة).",
            ],
          },
          {
            title: "المكتبة والرسم",
            body: [
              "أضف كتلة من المكتبة بالسحب إلى الرسم أو من لوحة الإضافة السريعة (Ctrl+/) — ويمكن التنقل والاختيار بلوحة المفاتيح بالكامل.",
              "شجرة الطبقات تعيد الترتيب بالسحب من مقبض كل صف، وتسمح بنقل أي كتلة بشجرتها بين الحاويات: أسقطها على صف لتستقر قبله/بعده بحسب اتجاه السحب، أو على شريط «إفلات هنا» أسفل أبناء أي حاوية موسّعة لتُلحق بنهايتها.",
              "النقل عبر الحاويات يمر بقيود صارمة تُعرض فور مخالفتها: حد عدد عناصر الصفحة، أقصى عمق للشجرة من موضع الهدف الجديد، قواعد ما تقبله كل حاوية، ولا يمكن إسقاط كتلة داخل أحد أبنائها — والبحث يعطّل السحب مؤقتًا.",
              "شجرة الطبقات تعرض مسار الكتلة المحددة (مسار تنقّل في أعلى الرسم) — حاويات مثل الأقسام والصفوف تُحذف بعنصرها كله مع تأكيد.",
              "خصائص كل كتلة تُحرر في اللوحة الجانبية، وتتحكم بإظهار/إخفائها على الجوال والتابلت والكمبيوتر من قسم المظهر.",
            ],
          },
          {
            title: "التحرير النصي المباشر",
            body: [
              "انقر نقرًا مزدوجًا على أي عنوان أو فقرة أو زر-رابط — أو حدده واضغط Enter — لتحرير النص في مكانه بنفس الطباعة والحجم.",
              "Enter يلتزم النص وتبقى الجلسة مفتوحة لتحرير عناصر أخرى، Esc يرجع الحقل لقيمته ويختم الجلسة، واللصق يُنزع لنص صرف.",
            ],
          },
          {
            title: "الحافظة عبر الصفحات",
            body: [
              "انسخ أي كتلة بشجرتها (زر الحافظة في شريط الأدوات العائم أو شجرة الطبقات أو لوحة الخصائص) — تبقى النسخة في متصفحك حتى بعد مغادرة الصفحة.",
              "من زر «لصق من الحافظة» في الشريط العلوي اختر من أحدث النسخ لأي صفحة: تُلصق بعد العنصر المحدد أو بنهاية الصفحة بمعرفات جديدة، مع أنماط الأجهزة وإعدادات الظهور كما نسختها.",
              "الحافظة تتسع لآخر 8 عناصر وتُفرغ بالكامل من أسفل قائمة اللصق — والتراجع (Ctrl+Z) يشمل اللصق كأي عملية.",
            ],
          },
          {
            title: "الحفظ التلقائي والمراجعات",
            body: [
              "كل تعديل يُحفظ تلقائيًا بعد ثانيتين — المؤشر العلوي يعرض: محفوظة / جارٍ الحفظ / غير محفوظ / خطأ / تعارض.",
              "كل حفظ يزيد رقم المراجعة؛ إذا حفظ مستخدم آخر قبلك يظهر حوار تعارض يعرض الفرق: «أبقِ تعديلاتي» أو «حمّل نسخة الخادم» — لا يُكتب فوق أحد بصمت.",
              "Ctrl+S يحفظ فورًا في أي وقت، وزر «استبعاد التعديلات غير المنشورة» (للصفحات المنشورة) يرمي تجارب المسودة ويعيدها حرفيًا لآخر نسخة منشورة.",
            ],
          },
          {
            title: "الإصدارات والقوالب",
            body: [
              "كل نشر ينشئ إصدارًا لكل لغة تغيّر محتواها — من حوار الإصدارات قارن واستعد أي نقطة (لقطة احتياطية تلقائية قبل الاستعادة).",
              "طبّق قالبًا جاهزًا بلغة واحدة في ثوانٍ، أو احفظ صفحتك الحالية قالبًا مخصصًا يعيد الفريق استخدامه — القوالب المدمجة محمية والقوالب المخصصة تُعاد تسميتها وتُحذف.",
            ],
          },
          {
            title: "النشر والجدولة",
            body: [
              "النشر مرتبط بمراجعة مسودة محفوظة: لا يُنشر أبدًا شيء مختلف عمّا رأيته على الشاشة، ويمكن نشر العربية دون الإنجليزية والعكس.",
              "جدولة النشر (أيقونة التقويم) تنشر المسودة آليًا في موعدها؛ الجدولة مرتبطة بمراجعة الحالي — تغيير المسودة قبل الموعد يُسقط النشر ويُشعرك، والإلغاء متاح في أي لحظة.",
            ],
          },
        ],
        shortcutsTitle: "اختصارات لوحة المفاتيح",
        shortcuts: [
          { keys: "Ctrl+Z", description: "تراجع عن آخر عملية" },
          { keys: "Ctrl+Shift+Z أو Ctrl+Y", description: "إعادة العملية" },
          { keys: "Ctrl+S", description: "حفظ فوري للمسودة" },
          { keys: "Ctrl+/", description: "لوحة الإضافة السريعة (تبديل)" },
          { keys: "Enter", description: "بدء التحرير المباشر على ورقية نصية محددة" },
          { keys: "Escape", description: "إلغاء جلسة التحرير / إلغاء التحديد / إغلاق الوضع التجريبي" },
          { keys: "نقر مزدوج", description: "تحرير نص مباشر داخل الرسم" },
          { keys: "F1 أو ؟", description: "فتح هذا الدليل" },
        ],
      },
      noSelection: "لا عنصر محدد",
      noSelectionBody: "اختر كتلة من المعاينة لتحرير خصائصها، أو أضف كتلة جديدة من المكتبة.",
      confirmDelete: "حذف هذه الكتلة؟",
      autosaveOn: "الحفظ التلقائي مفعّل",
      conflictTitle: "تعارض تحرير",
      conflictBody: "حُفظت نسخة أحدث من مستخدم آخر — لا يمكن الحفظ فوقها دون قرار منك.",
      conflictComparing: "جارٍ جلب نسخة الخادم للمقارنة…",
      conflictLocal: "نسختك المحلية",
      conflictServer: "نسخة الخادم",
      conflictSame: "مطابقة",
      conflictDiffers: "مختلفة",
      conflictChoice: "يمكنك الاحتفاظ بتعديلاتك (ستكتب فوق نسخة الخادم) أو تحميل نسخة الخادم (ستفقد تعديلاتك غير المحفوظة).",
      conflictKeepMine: "الاحتفاظ بتعديلاتي",
      conflictLoadServer: "تحميل نسخة الخادم",
      leaveTitle: "لديك تغييرات غير محفوظة",
      leaveBody: "إذا غادرت الآن قد تفقد تعديلاتك. احفظ أولًا أو أختر المغادرة دون حفظ.",
      leaveStay: "البقاء في المحرر",
      leaveDiscard: "المغادرة دون حفظ",
      leaveSaveAndGo: "حفظ ثم المغادرة",
      lastSaved: "آخر حفظ",
      lastEditor: "آخر محرر",
      unpublishedChanges: "تعديلات غير منشورة",
      unpublishedHint: "المسودة تحتوي تعديلات لم تُنشر بعد — الزوار يرون النسخة المنشورة",
      discard: "استبعاد التعديلات غير المنشورة",
      discardConfirm: "استبعاد التعديلات",
      discardDesc: "ستعود المسودة إلى آخر نسخة منشورة حرفيًا وتفقد كل التعديلات غير المنشورة. النسخة المنشورة نفسها لا تتأثر.",
      discarded: "استُبعدت التعديلات — عادت المسودة لآخر نسخة منشورة",
      schedule: "جدولة النشر",
      scheduleDesc: "سيُنشر محتوى المسودة الحالية آليًا في الموعد المحدد — عبر نواة النشر نفسها بكل مرايا أمانها (تحقق، إصدارات، تحويلات، تدقيق).",
      scheduleBindHint: "الجدولة مرتبطة بمراجعة المسودة الحالية ({rev}). إذا تغيّرت المسودة قبل الموعد يُسقط النشر آليًا ويُشعر صاحب الجدولة.",
      scheduleWhen: "موعد النشر",
      scheduleConfirm: "تأكيد الجدولة",
      scheduleCancelSchedule: "إلغاء الجدولة",
      scheduleCancelDesc: "لن يُنشر شيء آليًا — المسودة تبقى كما هي.",
      scheduleSetOk: "جُدول النشر الآلي في {time}",
      scheduleCancelOk: "أُلغيت الجدولة — لن يُنشر شيء آليًا",
      scheduleInvalidTime: "أدخل موعدًا صالحًا",
      schedulePastTime: "الموعد يجب أن يكون في المستقبل",
      scheduleNothingToCancel: "لا توجد جدولة قائمة",
      scheduleCurrent: "الجدولة الحالية",
      scheduledBadge: "مجدولة للنشر",
      scheduledShort: "مجدولة",
      emptyPageError: "لا يمكن نشر صفحة فارغة تمامًا باللغتين",
      archivedError: "الصفحة مؤرشفة — ألغِ الأرشفة أولًا",
      settingsDraftOnly: "هذه الإعدادات تحفظ في المسودة ولا تصل الزوار إلا عند النشر",
      publicTitleAr: "العنوان الظاهر (عربي)",
      publicTitleEn: "العنوان الظاهر (إنجليزي)",
      adminTitleAr: "الاسم الإداري (عربي) — داخلي",
      adminTitleEn: "الاسم الإداري (إنجليزي) — داخلي",
      slugDraftHint: "يُطبّق الرابط الجديد على الزوار عند النشر مع تحويل تلقائي من الرابط القديم",
      restoreScopeHint: "الاستعادة تكتب فوق المسودة الحالية (تُحفظ لقطة احتياطية تلقائيًا قبلها). اختر لغة واحدة أو اللغتين معًا.",
      reload: "إعادة التحميل",
      leaveWarning: "لديك تغييرات غير محفوظة — مغادرة الصفحة ستلغيها.",
      backToList: "عودة للقائمة",
      seo: "تحسينات البحث",
      seoTitle: "عنوان محركات البحث",
      seoDescription: "وصف محركات البحث",
      pageSettings: "إعدادات الصفحة",
      visibility: "الظهور",
      allowedRoles: "الأدوار المسموحة",
      dirtyIndicator: "غير محفوظ",
      hiddenOnMobile: "مخفي على الجوال",
      hiddenOnTablet: "مخفي على التابلت",
      hiddenOnDesktop: "مخفي على الكمبيوتر",
      background: "الخلفية",
      padding: "المسافة العمودية",
      style: "المظهر",
      items: "العناصر",
      addItem: "إضافة عنصر",
      removeItem: "إزالة",
      linkLabel: "نص الرابط",
      linkHref: "مسار الرابط",
      imageAlt: "النص البديل",
      imageSrc: "مصدر الصورة",
      mediaLibrary: "مكتبة الوسائط",
      uploadImage: "رفع صورة",
      templates: "القوالب",
      groups: {
        structure: "بنية الصفحة",
        home: "أقسام الرئيسية",
        pages: "أقسام الصفحات",
        generic: "عناصر عامة",
        layout: "تنسيق",
      },
    },
    templates: {
      title: "قوالب الصفحات",
      subtitle: "طبّق نموذجًا جاهزًا على المسودة أو احفظ المحتوى الحالي قالبًا لاستخدامه لاحقًا",
      saveAsTemplate: "حفظ كقالب",
      saveFromCurrent: "حفظ المحتوى الحالي كقالب جديد",
      saveHint: "يُحفظ محتوى لغة المسودة الحالية فقط — تقدر تكرر العملية من تبويب اللغة الأخرى",
      formNameAr: "اسم القالب (عربي)",
      formNameEn: "اسم القالب (إنجليزي)",
      formDescAr: "وصف مختصر (عربي) — اختياري",
      formDescEn: "وصف مختصر (إنجليزي) — اختياري",
      nameRequired: "أدخل اسم القالب بالعربية أو الإنجليزية",
      savedOk: "حُفظ القالب الجديد",
      saveFailed: "تعذّر حفظ القالب",
      apply: "تطبيق على المسودة",
      applyTo: "تطبيق",
      applyConfirmTitle: "تطبيق القالب على المسودة؟",
      applyConfirmBody: "سيُستبدل محتوى المسودة الحالية بمحتوى القالب",
      applyBackupNote: "تُحفظ نسخة احتياطية تلقائية من المحتوى الحالي في تاريخ الإصدارات قبل التطبيق — يمكنك استعادتها في أي وقت",
      applyLocaleNote: "التطبيق على لغة المسودة الحالية فقط — اللغة الأخرى لا تُمس",
      appliedOk: "طُبّق القالب على المسودة",
      builtin: "مدمج",
      custom: "مخصص",
      all: "الكل",
      usageCountOne: "استُخدم مرة واحدة",
      usageCountTwo: "استُخدم مرتين",
      usageCountFew: "استُخدم {n} مرات",
      usageCountMany: "استُخدم {n} مرة",
      createdBy: "أنشأه: {name}",
      rename: "إعادة تسمية",
      renameTitle: "تعديل بيانات القالب",
      renameDesc: "الاسم والوصف بلغتين — الحقول الفارغة تحتفظ بقيمها الحالية",
      renamedOk: "حُدّث القالب",
      renameFailed: "تعذّر تحديث القالب",
      empty: "لا قوالب مخصصة بعد",
      emptyBody: "احفظ صفحة قائمة كقالب لتظهر هنا ويعيد فريقك استخدامها",
      loadFailed: "تعذّر تحميل القوالب",
      delete: "حذف القالب",
      deleteConfirmTitle: "حذف هذا القالب؟",
      deleteConfirmBody: "الحذف نهائي ولا يمس الصفحات المطبَّق عليها سابقًا",
      deletedOk: "حُذف القالب",
      builtinReadonly: "القوالب المدمجة غير قابلة للحذف",
      missingLocale: "لا يحوي هذا القالب محتوى لهذه اللغة",
      previewLabel: "معاينة تخطيطية لبنية القالب {name}",
      previewCaption: "بنية القالب",
      nodesCountOne: "عنصر واحد",
      nodesCountTwo: "عنصران",
      nodesCountFew: "{n} عناصر",
      nodesCountMany: "{n} عنصرًا",
      conflict: "المسودة تغيّرت عندك أو عند غيرك — أعد المحاولة بعد التحميل",
    },
    media: {
      title: "مكتبة الوسائط",
      subtitle: "صور الموقع العامة — بديل النص مهم للوصول",
      upload: "رفع ملف",
      filename: "الملف",
      alt: "النص البديل",
      size: "الحجم",
      uploaded: "الرفع",
      actions: "إجراءات",
      copyUrl: "نسخ الرابط",
      delete: "حذف",
      deleted: "حُذف",
      uploadedOk: "رُفع الملف",
      empty: "لا وسائط بعد",
      confirmDelete: "حذف هذا الملف؟ لا يمكن التراجع.",
      search: "بحث",
      searchPlaceholder: "ابحث بالاسم أو النص البديل…",
      noResults: "لا نتائج مطابقة",
      allFolders: "كل المجلدات",
      folder: "المجلد",
      folderUpload: "مجلد الرفع",
      moveFolder: "نقل إلى مجلد",
      folderSaved: "حُدّث المجلد",
      inUse: "مستخدمة",
      unused: "غير مستخدمة",
      usedWhere: "أين تُستخدم؟",
      deleteBlockedTitle: "لا يمكن حذف وسيلة قيد الاستخدام",
      deleteBlockedDesc: "هذه الوسيلة مشار إليها في المواضع التالية — أزل الاستخدام أولًا ثم أعد المحاولة:",
      usagePagePublished: "صفحة منشورة",
      usagePageDraft: "مسودة صفحة",
      usagePageOg: "صورة مشاركة (SEO)",
      usageTemplate: "قالب صفحة",
      usageArchived: "مؤرشفة",
      usageFilterLabel: "تصفية بحالة الاستخدام",
      usageFilterAll: "كل الوسائط",
      usageFilterInUse: "المستخدمة",
      usageFilterUnused: "غير المستخدمة",
    },
    menus: {
      title: "القوائم",
      subtitle: "روابط الترويسة والتذييل وترتيبها",
      header: "قائمة الترويسة",
      footer: "قائمة التذييل",
      labelAr: "التسمية (عربي)",
      labelEn: "التسمية (إنجليزي)",
      linkType: "نوع الرابط",
      pageLink: "صفحة من المحتوى",
      customUrl: "رابط مخصص",
      enabled: "مفعّل",
      add: "إضافة رابط",
      save: "حفظ القائمة",
      saved: "حُفظت القائمة",
      remove: "إزالة",
      pagesPlaceholder: "اختر الصفحة…",
    },
    settings: {
      title: "إعدادات الموقع",
      subtitle: "بيانات التواصل والروابط الرسمية — تظهر في التذييل وصفحة التواصل",
      contact: "بيانات التواصل",
      social: "الروابط الاجتماعية",
      email: "البريد الإلكتروني",
      phone: "الهاتف",
      address: "العنوان",
      github: "GitHub",
      save: "حفظ الإعدادات",
      saved: "حُفظت الإعدادات",
      announcement: "الإعلان العلوي",
      announcementSubtitle: "شريط أعلى الموقع لكل الزوار — يظهر حتى يخفيه الزائر من متصفحه، ويعود تلقائيًا عند تحديثه",
      announcementMessageAr: "نص الإعلان (عربي)",
      announcementMessageEn: "نص الإعلان (إنجليزي)",
      announcementCtaLabelAr: "تسمية الزر (عربي)",
      announcementCtaLabelEn: "تسمية الزر (إنجليزي)",
      announcementCtaUrl: "رابط الزر (اختياري)",
      announcementVariant: "النمط",
      announcementVariants: {
        info: "معلوماتي",
        warning: "تحذيري",
        success: "نجاح",
        brand: "هوية",
      },
      announcementEnabled: "مفعّل",
      announcementStart: "تاريخ البدء (اختياري)",
      announcementEnd: "تاريخ الانتهاء (اختياري)",
      track: {
        title: "سياسة روابط المتابعة",
        subtitle: "من يطّلع على بطاقة المتابعة ومن يرد عبرها — تُطبق فورًا على كل عرض ورد قادم",
        forceLogin: "فرض تسجيل الدخول على الجميع",
        forceLoginHint: "أولوية قصوى: يلغي مؤقتًا كل أوضاع الروابط والاستثناءات — حامل الرابط يُطلب منه الدخول دائمًا. أوقفه لعودة الأوضاع المختارة أدناه.",
        requestsMode: "وضع طلبات المشاريع",
        inquiriesMode: "وضع الاستفسارات",
        ttl: "مدة صلاحية الرابط (أيام)",
        ttlHint: "من 1 إلى 3650 يومًا — تنطبق على الروابط الجديدة عند الإنشاء والتجديد",
        allowGuestAttachments: "السماح لمستلمي الرابط بإرفاق ملفات بردّهم",
        allowGuestAttachmentsHint: "عند التعطيل يُرفض رفع المرفقات خادميًا حتى لو سمح الوضع بالرد",
        modes: {
          login_required: "الدخول مطلوب — الاطلاع والرد بحساب فقط",
          link_view: "الرابط للاطلاع فقط — الرد بحساب فقط",
          link_reply: "الرابط للاطلاع والرد — بلا حساب",
          link_view_login_reply: "الرابط للاطلاع — الرد بحساب مخوّل",
        },
        preview: "السلوك الفعلي الآن",
        previewView: "حامل الرابط يطّلع",
        previewReply: "حامل الرابط يرد بلا حساب",
        previewOwnerReply: "صاحب البطاقة يرد من حسابه",
        yes: "مسموح",
        no: "ممنوع",
        priorityNote: "الأولوية: فرض الدخول ← استثناء البطاقة (من لوحتها) ← وضع النوع هنا",
        invalidTtl: "مدة الصلاحية يجب أن تكون عددًا صحيحًا بين 1 و 3650",
      },
    },
    audit: {
      title: "سجل التدقيق",
      subtitle: "من فعل ماذا ومتى — كل العمليات الحساسة",
      actor: "الفاعل",
      action: "الإجراء",
      entity: "السجل",
      date: "الوقت",
      details: "التفاصيل",
      empty: "لا أحداث",
    },
    outbox: {
      title: "صندوق الصادر",
      subtitle: "حالة تشغيل البريد. قبول خادم SMTP لا يؤكد وصول الرسالة لصندوق المستلم.",
      to: "إلى",
      subject: "الموضوع",
      status: "الحالة",
      sent: "قبله خادم SMTP",
      devLogged: "مسجلة (تطوير)",
      queued: "في الانتظار",
      retry: "بانتظار إعادة المحاولة",
      leased: "محجوزة للعامل",
      sending: "جارٍ الإرسال",
      uncertain: "قبول غير مؤكد — تحتاج مراجعة",
      unknown: "حالة تاريخية غير معروفة",
      attempts: "المحاولات",
      nextAttempt: "المحاولة القادمة",
      errorCode: "رمز الخطأ",
      failed: "فشلت",
      date: "الوقت",
      empty: "لا رسائل",
      emptyBody: "ستظهر هنا رسائل التحقق والاستعادة والإشعارات.",
    },
    savedReplies: {
      title: "الردود المحفوظة",
      subtitle: "قوالب جاهزة للردود المتكررة في المحادثات",
      manage: "إدارة الردود المحفوظة",
      name: "اسم القالب",
      namePlaceholder: "مثال: طلب مزيد من التفاصيل",
      content: "نص الرد",
      contentPlaceholder: "اكتب نص الرد كما سيظهر للعميل…",
      add: "إضافة رد",
      edit: "تحرير",
      delete: "حذف",
      save: "حفظ",
      saved: "حُفظ الرد",
      deleted: "حُذف الرد",
      confirmDelete: "سيُحذف هذا الرد نهائيًا ولا يمكن التراجع.",
      useReply: "رد محفوظ",
      insert: "إدراج",
      empty: "لا ردود محفوظة",
      emptyBody: "أنشئ قوالب للردود المتكررة ليستخدمها الفريق بضغطة واحدة.",
    },
  },
  announce: {
    ariaLabel: "إعلان",
    dismiss: "إخفاء الإعلان",
  },
};
