import type { PortalContent } from "./types";

/** ترجمات المنصة — العربية (المصدر) */
export const portalAr: PortalContent = {
  auth: {
    loginTitle: "تسجيل الدخول",
    loginSubtitle: "أدخل بياناتك للوصول إلى حسابك",
    loginButton: "دخول",
    logout: "تسجيل الخروج",
    registerTitle: "إنشاء حساب",
    registerSubtitle: "حساب عميل جديد — للطاقم تُستخدم الدعوات",
    registerButton: "إنشاء الحساب",
    registerSuccessTitle: "أُنشئ حسابك",
    registerSuccessBody: "أرسلنا رابط تأكيد إلى بريدك الإلكتروني. أكّده لتفعيل الحساب وبدء تقديم الطلبات.",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    passwordHint: "8 محارف فأكثر، حروف وأرقام",
    currentPassword: "كلمة المرور الحالية",
    newPassword: "كلمة المرور الجديدة",
    confirmPassword: "تأكيد كلمة المرور",
    forgotTitle: "استعادة كلمة المرور",
    forgotHint: "أدخل بريدك وسنرسل رابط إعادة التعيين إن وُجد حساب مرتبط به.",
    forgotButton: "إرسال رابط الاستعادة",
    forgotSent: "إن كان البريد مسجلًا فستصلك رسالة خلال دقائق.",
    forgotSentDev: "وضع التطوير: الرابط أدناه (لن يظهر في الإنتاج).",
    resetTitle: "كلمة مرور جديدة",
    resetButton: "ضبط كلمة المرور",
    resetSuccess: "غُيّرت كلمة المرور — سجّل الدخول من جديد.",
    verifyTitle: "تأكيد البريد الإلكتروني",
    verifyOk: "تم تأكيد بريدك",
    verifyOkBody: "حسابك مفعّل الآن. سجّل الدخول لبدء استخدام بوابة العميل.",
    verifyAlready: "كان بريدك مؤكدًا مسبقًا",
    verifyInvalid: "رابط غير صالح",
    verifyInvalidBody: "انتهت صلاحية الرابط أو استُخدم من قبل. اطلب رابطًا جديدًا من صفحة الدخول.",
    noAccount: "ليس لديك حساب؟",
    haveAccount: "لديك حساب بالفعل؟",
    backHome: "العودة للموقع",
    pendingVerification: "بريدك غير مؤكد بعد",
    pendingVerificationBody: "تأكيد البريد يفعّل إرسال الطلبات والمحادثات. راجع بريدك أو أعد إرسال رابط التأكيد.",
    resendVerification: "إعادة إرسال رابط التأكيد",
    devOutboxHint: "وضع تطوير البريد: الرسائل تُسجل في صندوق الصادر داخل لوحة الإدارة ولا تُرسل فعليًا.",
    errors: {
      invalid: "بيانات غير صالحة",
      wrongPassword: "كلمة المرور الحالية غير صحيحة",
      emailTaken: "البريد مستخدم في حساب آخر",
      rateLimited: "محاولات كثيرة — انتظر قليلًا ثم أعد المحاولة",
      credentials: "تعذّر تسجيل الدخول — تحقق من البريد وكلمة المرور (أو أن الحساب غير متاح)",
      locked: "قُفل الحساب مؤقتًا بسبب محاولات دخول فاشلة متكررة",
      passwordWeak: "كلمة المرور ضعيفة: 8 محارف فأكثر مع حروف وأرقام",
      passwordMismatch: "كلمتا المرور غير متطابقتين",
      nameInvalid: "الاسم غير صالح",
      emailInvalid: "البريد الإلكتروني غير صالح",
      required: "هذا الحقل مطلوب",
      generic: "حدث خطأ غير متوقع — أعد المحاولة",
    },
  },
  account: {
    nav: {
      dashboard: "اللوحة",
      requests: "طلباتي",
      newRequest: "طلب جديد",
      inquiries: "الاستفسارات",
      notifications: "الإشعارات",
      profile: "الملف الشخصي",
      security: "الأمان والجلسات",
      logout: "تسجيل الخروج",
      backSite: "الموقع العام",
    },
    dashboard: {
      title: "لوحة حسابك",
      welcome: "مرحبًا",
      welcomeWithName: "مرحبًا، {name}",
      openRequests: "طلبات مفتوحة",
      awaitingReply: "بانتظار ردك",
      unreadNotifications: "إشعارات غير مقروءة",
      totalRequests: "إجمالي الطلبات",
      openInquiries: "استفسارات مفتوحة",
      totalInquiries: "إجمالي الاستفسارات",
      recentUpdates: "آخر التحديثات",
      emptyTitle: "لا طلبات بعد",
      emptyBody: "أنشئ طلبك الأول — ناقش فكرتك أو اطلب عرض سعر.",
      createRequest: "إنشاء طلب",
      viewAll: "عرض الكل",
    },
    requests: {
      title: "طلباتي",
      subtitle: "تابع حالة طلباتك ومحادثاتها",
      create: "طلب جديد",
      refCode: "الرقم المرجعي",
      status: "الحالة",
      service: "الخدمة",
      created: "تاريخ الإنشاء",
      lastActivity: "آخر نشاط",
      empty: "لا طلبات بعد",
      emptyBody: "ابدأ بإنشاء طلب جديد وسيظهر هنا مع محادثته.",
      viewDetails: "عرض التفاصيل",
      cancelEdit: "إلغاء",
      submitSuccess: "أُرسل طلبك",
      submitSuccessBody: "رقمه المرجعي أدناه — سيتواصل معك الفريق قريبًا.",
      claimTitle: "ربط طلب سابق",
      claimBody: "أدخل الرقم المرجعي لطلب قدمته قبل إنشاء الحساب، وسنرسل رابط تأكيد لربطه بحسابك.",
      claimButton: "إرسال رابط الربط",
      claimSent: "إن كان الطلب موجودًا فستصلك رسالة تأكيد الربط.",
      claimVerifyTitle: "ربط الطلب بحسابك",
      claimVerifyOk: "رُبط الطلب بحسابك بنجاح",
      statuses: {
        new: "جديد",
        in_review: "قيد المراجعة",
        awaiting_info: "بانتظار معلومات",
        in_progress: "قيد المعالجة",
        responded: "تم الرد",
        closed: "مغلق",
        cancelled: "ملغى",
      },
      services: {
        web: "تطوير الويب",
        mobile: "تطبيقات الجوال",
        systems: "الأنظمة الإدارية",
        ux: "تجربة المستخدم",
        automation: "الأتمتة والتكامل",
        maintenance: "الصيانة والدعم",
        unsure: "غير محدد",
      },
      draftRestored: "استُعدت مسودة طلبك السابقة",
      draftSaved: "حُفظت المسودة",
      draftCleared: "مُسحت المسودة",
      search: "بحث",
      searchPlaceholder: "ابحث بالرقم المرجعي أو الخدمة أو الحالة…",
      noResults: "لا نتائج مطابقة لبحثك",
      clearSearch: "مسح البحث",
      awaitingYou: "بانتظار ردك",
      awaitingHours: "{n} ساعة",
      awaitingDays: "{n} يوم",
    },
    detail: {
      conversation: "المحادثة",
      internalHidden: "الملاحظات الداخلية للفريق لا تظهر هنا",
      replyPlaceholder: "اكتب ردك أو إضافتك…",
      send: "إرسال",
      sending: "جارٍ الإرسال…",
      attachFile: "إرفاق ملف",
      attachments: "المرفقات",
      download: "تنزيل",
      history: "السجل",
      statusTimeline: "مسار الحالة",
      assignedTo: "المسؤول",
      unassigned: "غير معيّن",
      closedNote: "سبب الإغلاق",
      replySuccess: "أُرسل ردك",
      replyEmpty: "اكتب نص الرسالة أولًا",
      fileTooLarge: "الملف أكبر من الحد المسموح",
      fileTypeInvalid: "نوع الملف غير مسموح",
      you: "أنت",
      staff: "الفريق",
      system: "النظام",
      noMessages: "لا رسائل بعد — الفريق سيرد قريبًا",
      requestInfo: "بيانات الطلب",
      priority: "الأولوية",
      timeline: "الإطار الزمني",
      budget: "الميزانية",
      currency: "العملة",
      contactPref: "قناة التواصل المفضلة",
      reference: "رابط مرجعي",
      print: "طباعة الطلب",
    },
    inquiries: {
      title: "استفساراتي",
      subtitle: "أسئلة سريعة وأجوبة فريق سُحُب في محادثة واحدة",
      create: "استفسار جديد",
      refCode: "الرقم المرجعي",
      subject: "الموضوع",
      category: "التصنيف",
      categories: {
        general: "عام",
        services: "الخدمات",
        pricing: "الأسعار",
        support: "الدعم",
        other: "أخرى",
      },
      status: "الحالة",
      statuses: {
        new: "جديد",
        in_review: "قيد المراجعة",
        awaiting_info: "بانتظار معلومات",
        responded: "تم الرد",
        closed: "مغلق",
      },
      all: "عرض الكل",
      openShortcut: "استفسارات مفتوحة",
      messages: "الرسائل",
      created: "تاريخ الإنشاء",
      lastActivity: "آخر نشاط",
      empty: "لا استفسارات بعد",
      emptyBody: "اطرح سؤالك القصير هنا وسيرد الفريق في نفس المحادثة.",
      noResults: "لا نتائج مطابقة لبحثك",
      viewDetails: "عرض المحادثة",
      back: "كل الاستفسارات",
      notFound: "الاستفسار غير موجود أو لا تملك صلاحية عرضه",
      conversation: "المحادثة",
      meta: "تفاصيل الاستفسار",
      assignedTo: "المسؤول",
      unassigned: "غير معيَّن بعد",
      you: "أنت",
      team: "فريق سُحُب",
      system: "النظام",
      noMessages: "لا رسائل بعد",
      statusTimeline: "سجل الحالة",
      replyPlaceholder: "اكتب ردك أو استفسارك الإضافي…",
      send: "إرسال",
      sending: "يُرسل…",
      replySuccess: "أُرسل ردك",
      replyEmpty: "اكتب نص الرسالة أولًا",
      closedNote: "هذا الاستفسار مغلق — ابدأ استفسارًا جديدًا إن احتجت مساعدة إضافية.",
      formTitle: "استفسار جديد",
      formIntro: "سؤال قصير؟ اكتبه هنا وسيتولى الفريق الرد في محادثة خاصة.",
      formSubject: "الموضوع",
      formSubjectPlaceholder: "مثال: هل تقدمون صيانة شهرية؟",
      formCategory: "التصنيف",
      formMessage: "سؤالك",
      formMessagePlaceholder: "اكتب سؤالك بوضوح — التفاصيل تساعدنا على رد أدق.",
      formSubmit: "إرسال الاستفسار",
      formCancel: "إلغاء",
      createdOk: "أُرسل استفسارك",
      createdOkBody: "رقمه المرجعي أدناه — سيرد الفريق قريبًا.",
      createdOkOpen: "متابعة المحادثة",
      attachments: "المرفقات",
      download: "تنزيل",
      print: "طباعة الاستفسار",
    },
    notifications: {
      title: "الإشعارات",
      markRead: "تعليم كمقروء",
      markAllRead: "تعليم الكل كمقروء",
      empty: "لا إشعارات",
      types: {
        new_request: "طلب جديد",
        new_inquiry: "استفسار جديد",
        request_assigned: "تعيين طلب",
        reply_received: "رد جديد",
        info_requested: "طلب معلومات",
        status_changed: "تغيير حالة",
        content_published: "نشر محتوى",
        account: "الحساب",
      },
    },
    profile: {
      title: "الملف الشخصي",
      name: "الاسم",
      phone: "الهاتف",
      company: "الشركة",
      language: "لغة الواجهة المفضلة",
      save: "حفظ التغييرات",
      saved: "حُفظت التغييرات",
      emailReadonly: "البريد الإلكتروني لا يُغير من هنا — تواصل مع الدعم",
      verified: "بريد مؤكد",
      notVerified: "بريد غير مؤكد",
    },
    security: {
      title: "الأمان والجلسات",
      changePassword: "تغيير كلمة المرور",
      passwordChanged: "غُيّرت كلمة المرور",
      passwordChangedBody: "أُبطلت كل الجلسات — سجّل الدخول من جديد.",
      sessions: "الجلسات النشطة",
      currentSession: "هذا الجهاز",
      thisDevice: "هذا الجهاز",
      revoke: "إبطال",
      revokeAll: "إبطال البقية",
      revoked: "أُبطلت الجلسة",
      lastActive: "آخر ظهور",
      created: "أُنشئت",
      unknownDevice: "جهاز غير معروف",
      noSessions: "لا جلسات نشطة أخرى",
      relogin: "سجّل الدخول من جديد",
    },
  },
  admin: {
    nav: {
      dashboard: "اللوحة",
      users: "المستخدمون",
      requests: "الطلبات",
      inquiries: "الاستفسارات",
      notifications: "الإشعارات",
      pages: "الصفحات",
      media: "الوسائط",
      menus: "القوائم",
      settings: "الإعدادات",
      audit: "سجل التدقيق",
      outbox: "صندوق الصادر",
      backSite: "الموقع العام",
      logout: "تسجيل الخروج",
    },
    search: {
      trigger: "بحث شامل",
      placeholder: "ابحث في المستخدمين والطلبات والاستفسارات والصفحات…",
      quickNav: "تنقل سريع",
      results: "النتائج",
      searching: "جارٍ البحث…",
      noResults: "لا نتائج مطابقة لبحثك",
      noResultsHint: "جرّب كلمة مختلفة أو رقم مرجع (مثل S7-)",
      openHint: "افتح لعرض النتيجة",
    },
    dashboard: {
      title: "لوحة الإدارة",
      totalUsers: "إجمالي المستخدمين",
      activeUsers: "حسابات نشطة",
      pendingUsers: "بانتظار التحقق",
      openRequests: "طلبات مفتوحة",
      newRequests: "طلبات جديدة",
      awaitingInfo: "بانتظار معلومات",
      unansweredRequests: "طلبات بلا رد",
      openInquiries: "استفسارات مفتوحة",
      publishedPages: "صفحات منشورة",
      draftPages: "مسودات صفحات",
      requestsByStatus: "الطلبات حسب الحالة",
      recentActivity: "أحدث الأحداث",
      recentRequests: "أحدث الطلبات",
      viewAll: "عرض الكل",
      noData: "لا بيانات بعد",
      last7days: "آخر 7 أيام",
      rangeLabel: "اختيار المدى الزمني",
      range7: "آخر 7 أيام",
      range30: "آخر 30 يومًا",
      range90: "آخر 90 يومًا",
      overdueReplies: "ردود متأخرة",
      overdueHint: "بانتظار رد الفريق أكثر من 24 ساعة",
    },
    users: {
      title: "المستخدمون",
      subtitle: "إدارة الحسابات والأدوار والحالات",
      search: "بحث",
      searchPlaceholder: "اسم أو بريد…",
      role: "الدور",
      status: "الحالة",
      statusActive: "نشط",
      statusPending: "بانتظار التحقق",
      statusSuspended: "موقوف",
      createdAt: "الإنشاء",
      lastLogin: "آخر دخول",
      requests: "الطلبات",
      actions: "إجراءات",
      suspend: "إيقاف",
      activate: "تفعيل",
      changeRole: "تغيير الدور",
      invite: "دعوة",
      inviteTitle: "دعوة مستخدم",
      inviteEmail: "بريد المدعو",
      inviteRole: "الدور الممنوح",
      inviteSend: "إرسال الدعوة",
      inviteSent: "أُرسلت الدعوة",
      edit: "تعديل",
      save: "حفظ",
      saved: "حُفظ",
      cancel: "إلغاء",
      confirmSuspend: "إيقاف هذا الحساب؟ ستُبطل جلساته فورًا.",
      confirmActivate: "إعادة تفعيل هذا الحساب؟",
      confirmLastAdmin: "لا يمكن إيقاف أو تخفيض آخر مدير نظام نشط.",
      emailVerified: "بريد مؤكد",
      notVerified: "بريد غير مؤكد",
      never: "لم يسجل دخولًا",
      filterAll: "الكل",
      userUpdated: "حُدّث المستخدم",
      lastAdminError: "الإجراء مرفوض: آخر مدير نظام نشط",
      sendReset: "إرسال استعادة كلمة المرور",
      resetSent: "أُرسل رابط الاستعادة",
      viewProfile: "عرض الملف",
      detail: {
        title: "ملف المستخدم",
        back: "عودة إلى المستخدمين",
        accountInfo: "بيانات الحساب",
        totalRequests: "إجمالي الطلبات",
        openRequests: "طلبات مفتوحة",
        userRequests: "طلبات المستخدم",
        activityLog: "آخر الأنشطة",
        sessionsCount: "الجلسات النشطة",
        noRequests: "لا طلبات لهذا المستخدم بعد",
        suspendedAt: "تاريخ الإيقاف",
        lastSeen: "آخر ظهور",
      },
    },
    requests: {
      title: "الطلبات",
      subtitle: "متابعة العملاء والرد وتوزيع العمل",
      searchPlaceholder: "رقم مرجعي، بريد، اسم، نص…",
      filterStatus: "الحالة",
      filterPriority: "الأولوية",
      filterService: "الخدمة",
      filterAssignee: "المسؤول",
      filterOverdue: "متأخر الرد +24 ساعة",
      filterAll: "الكل",
      unassigned: "غير معيّن",
      assign: "تعيين",
      assignTo: "تعيين إلى",
      assignToMe: "تعيين لي",
      changeStatus: "تغيير الحالة",
      reply: "رد على العميل",
      internalNote: "ملاحظة داخلية",
      internalNoteHint: "تظهر للطاقم فقط — لا تصل للعميل",
      archive: "أرشفة",
      restore: "استعادة",
      archived: "مؤرشف",
      clientReply: "رد العميل",
      staffReply: "رد الطاقم",
      client: "العميل",
      none: "—",
      lastActivity: "آخر نشاط",
      viewDetails: "التفاصيل",
      bulkArchive: "أرشفة المحدد",
      selected: "محدد",
      priority: "الأولوية",
      requestType: "نوع الطلب",
      discussion: "نقاش",
      quote: "عرض سعر",
      statuses: {
        new: "جديد",
        in_review: "قيد المراجعة",
        awaiting_info: "بانتظار معلومات",
        in_progress: "قيد المعالجة",
        responded: "تم الرد",
        closed: "مغلق",
        cancelled: "ملغى",
      },
      priorities: {
        low: "منخفضة",
        normal: "عادية",
        high: "عالية",
        urgent: "عاجلة",
      },
      services: {
        web: "الويب",
        mobile: "الجوال",
        systems: "الأنظمة",
        ux: "تجربة المستخدم",
        automation: "الأتمتة",
        maintenance: "الصيانة",
        unsure: "غير محدد",
      },
      budget: "الميزانية",
      currency: "العملة",
      timelinePref: "الإطار الزمني",
      contactPref: "قناة التواصل",
      contact: "التواصل",
      reference: "مرجع",
      history: "السجل",
      conversation: "المحادثة",
      messages: "رسائل",
      empty: "لا طلبات مطابقة",
      emptyBody: "عدّل عوامل التصفية أو انتظر وصول طلبات جديدة.",
      closeReason: "سبب الإغلاق/الإلغاء",
      closeReasonPlaceholder: "سبب يظهر للعميل…",
      statusNotePlaceholder: "ملاحظة على تغيير الحالة (اختياري)…",
      applyStatus: "تطبيق",
      sentReply: "أُرسل الرد",
      sentNote: "أُضيفت الملاحظة الداخلية",
      clientView: "معاينة ما يراه العميل",
      export: "تصدير CSV",
      exportOk: "صُدّر ملف الطلبات",
      awaitingTeam: "بانتظار رد الفريق",
      overdueReply: "رد متأخر",
      agingHours: "{n} ساعة",
      agingDays: "{n} يوم",
      presetSave: "حفظ التصفية",
      presetName: "اسم التصفية",
      presetSaved: "حُفظت التصفية",
      presetRemoved: "حُذفت التصفية",
      presetApply: "تطبيق التصفية المحفوظة",
      presetDelete: "حذف التصفية المحفوظة",
      print: "طباعة الطلب",
    },
    inquiries: {
      title: "الاستفسارات",
      subtitle: "أسئلة عامة وتواصل مباشر",
      subject: "الموضوع",
      category: "التصنيف",
      categories: {
        general: "عام",
        services: "الخدمات",
        pricing: "الأسعار",
        support: "الدعم",
        other: "أخرى",
      },
      new: "جديد",
      reply: "رد",
      assign: "تعيين",
      conversation: "المحادثة",
      empty: "لا استفسارات",
      statuses: {
        new: "جديد",
        in_review: "قيد المراجعة",
        awaiting_info: "بانتظار معلومات",
        responded: "تم الرد",
        closed: "مغلق",
      },
      export: "تصدير CSV",
      exportOk: "صُدّر ملف الاستفسارات",
      archive: "أرشفة",
      restore: "استعادة",
      archived: "مؤرشف",
      bulkArchive: "أرشفة المحدد",
      selected: "محدد",
      print: "طباعة الاستفسار",
    },
    notifications: {
      title: "الإشعارات",
      subtitle: "تحديثات الطلبات والاستفسارات والمحتوى الموجهة للفريق",
      markRead: "تعليم كمقروء",
      markAllRead: "تعليم الكل كمقروء",
      empty: "لا إشعارات",
      types: {
        new_request: "طلب جديد",
        new_inquiry: "استفسار جديد",
        request_assigned: "تعيين طلب",
        reply_received: "رد جديد",
        info_requested: "طلب معلومات",
        status_changed: "تغيير حالة",
        content_published: "نشر محتوى",
        account: "الحساب",
      },
    },
    pages: {
      title: "الصفحات",
      subtitle: "محتوى الموقع — تحرير ونشر وإصدارات",
      createPage: "صفحة جديدة",
      pageTitle: "الصفحة",
      rowActions: "إجراءات — {title}",
      slug: "المسار",
      slugHint: "أحرف لاتينية صغيرة وأرقام وشرطات — يترك فارغًا للرئيسية فقط",
      status: "الحالة",
      order: "الترتيب",
      updated: "آخر تحديث",
      edit: "تحرير",
      duplicate: "نسخ",
      archive: "أرشفة",
      restore: "استعادة",
      preview: "معاينة",
      published: "منشورة",
      draft: "مسودة",
      inReview: "قيد المراجعة",
      archivedStatus: "مؤرشفة",
      visibility: "الظهور",
      visibilityPublic: "عامة",
      visibilityAuth: "للمسجلين",
      visibilityRole: "لأدوار محددة",
      home: "الرئيسية",
      setHome: "تعيين كرئيسية",
      notHome: "ليست الرئيسية",
      newPageTitle: "صفحة جديدة",
      empty: "لا صفحات",
      emptyBody: "أنشئ أول صفحة من زر «صفحة جديدة».",
      versions: "الإصدارات",
      versionHistory: "تاريخ الإصدارات",
      restoreVersion: "استعادة هذا الإصدار",
      currentVersion: "الإصدار الحالي",
      compare: "مقارنة",
      editorTouched: "عدّلها محرر — البذرة لن تلمسها",
    },
    editor: {
      title: "محرر الصفحة",
      saved: "محفوظة",
      saving: "جارٍ الحفظ…",
      saveFailed: "فشل الحفظ — أعد المحاولة",
      unsaved: "تغييرات غير محفوظة",
      publish: "نشر",
      publishDisabled: "النشر بصلاحية مستقلة",
      publishedOk: "نُشرت الصفحة",
      ar: "العربية",
      en: "الإنجليزية",
      blocks: "الكتل",
      library: "المكتبة",
      canvas: "المعاينة",
      properties: "الخصائص",
      addBlock: "إضافة",
      insertHere: "أدرج هنا",
      delete: "حذف",
      duplicate: "تكرار",
      moveUp: "أعلى",
      moveDown: "أسفل",
      undo: "تراجع",
      redo: "إعادة",
      preview: "معاينة",
      deviceDesktop: "كمبيوتر",
      deviceTablet: "تابلت",
      deviceMobile: "جوال",
      quickAdd: "إضافة سريعة لكتلة",
      searchBlocks: "ابحث في الكتل بالاسم…",
      noBlocks: "لا كتل مطابقة لبحثك",
      selectedBlock: "العنصر المحدد",
      noSelection: "لا عنصر محدد",
      noSelectionBody: "اختر كتلة من المعاينة لتحرير خصائصها، أو أضف كتلة جديدة من المكتبة.",
      confirmDelete: "حذف هذه الكتلة؟",
      autosaveOn: "الحفظ التلقائي مفعّل",
      conflictTitle: "تعارض تحرير",
      conflictBody: "حُفظت نسخة أحدث من مستخدم آخر. أعد التحميل للاطلاع عليها قبل المتابعة.",
      reload: "إعادة التحميل",
      leaveWarning: "لديك تغييرات غير محفوظة — مغادرة الصفحة ستلغيها.",
      backToList: "عودة للقائمة",
      seo: "تحسينات البحث",
      seoTitle: "عنوان محركات البحث",
      seoDescription: "وصف محركات البحث",
      pageSettings: "إعدادات الصفحة",
      visibility: "الظهور",
      allowedRoles: "الأدوار المسموحة",
      dirtyIndicator: "غير محفوظ",
      hiddenOnMobile: "مخفي على الجوال",
      hiddenOnTablet: "مخفي على التابلت",
      hiddenOnDesktop: "مخفي على الكمبيوتر",
      background: "الخلفية",
      padding: "المسافة العمودية",
      style: "المظهر",
      items: "العناصر",
      addItem: "إضافة عنصر",
      removeItem: "إزالة",
      linkLabel: "نص الرابط",
      linkHref: "مسار الرابط",
      imageAlt: "النص البديل",
      imageSrc: "مصدر الصورة",
      mediaLibrary: "مكتبة الوسائط",
      uploadImage: "رفع صورة",
      groups: {
        home: "أقسام الرئيسية",
        pages: "أقسام الصفحات",
        generic: "عناصر عامة",
        layout: "تنسيق",
      },
    },
    media: {
      title: "مكتبة الوسائط",
      subtitle: "صور الموقع العامة — بديل النص مهم للوصول",
      upload: "رفع ملف",
      filename: "الملف",
      alt: "النص البديل",
      size: "الحجم",
      uploaded: "الرفع",
      actions: "إجراءات",
      copyUrl: "نسخ الرابط",
      delete: "حذف",
      deleted: "حُذف",
      uploadedOk: "رُفع الملف",
      empty: "لا وسائط بعد",
      confirmDelete: "حذف هذا الملف؟ الروابط المستخدمة له ستتعطل.",
    },
    menus: {
      title: "القوائم",
      subtitle: "روابط الترويسة والتذييل وترتيبها",
      header: "قائمة الترويسة",
      footer: "قائمة التذييل",
      labelAr: "التسمية (عربي)",
      labelEn: "التسمية (إنجليزي)",
      linkType: "نوع الرابط",
      pageLink: "صفحة من المحتوى",
      customUrl: "رابط مخصص",
      enabled: "مفعّل",
      add: "إضافة رابط",
      save: "حفظ القائمة",
      saved: "حُفظت القائمة",
      remove: "إزالة",
      pagesPlaceholder: "اختر الصفحة…",
    },
    settings: {
      title: "إعدادات الموقع",
      subtitle: "بيانات التواصل والروابط الرسمية — تظهر في التذييل وصفحة التواصل",
      contact: "بيانات التواصل",
      social: "الروابط الاجتماعية",
      email: "البريد الإلكتروني",
      phone: "الهاتف",
      address: "العنوان",
      github: "GitHub",
      save: "حفظ الإعدادات",
      saved: "حُفظت الإعدادات",
      announcement: "الإعلان العلوي",
      announcementSubtitle: "شريط أعلى الموقع لكل الزوار — يظهر حتى يخفيه الزائر من متصفحه، ويعود تلقائيًا عند تحديثه",
      announcementMessageAr: "نص الإعلان (عربي)",
      announcementMessageEn: "نص الإعلان (إنجليزي)",
      announcementCtaLabelAr: "تسمية الزر (عربي)",
      announcementCtaLabelEn: "تسمية الزر (إنجليزي)",
      announcementCtaUrl: "رابط الزر (اختياري)",
      announcementVariant: "النمط",
      announcementVariants: {
        info: "معلوماتي",
        warning: "تحذيري",
        success: "نجاح",
        brand: "هوية",
      },
      announcementEnabled: "مفعّل",
      announcementStart: "تاريخ البدء (اختياري)",
      announcementEnd: "تاريخ الانتهاء (اختياري)",
    },
    audit: {
      title: "سجل التدقيق",
      subtitle: "من فعل ماذا ومتى — كل العمليات الحساسة",
      actor: "الفاعل",
      action: "الإجراء",
      entity: "السجل",
      date: "الوقت",
      details: "التفاصيل",
      empty: "لا أحداث",
    },
    outbox: {
      title: "صندوق الصادر",
      subtitle: "رسائل البريد المرسلة أو المسجلة — وضع التطوير يسجل بلا إرسال فعلي",
      to: "إلى",
      subject: "الموضوع",
      status: "الحالة",
      sent: "أُرسلت",
      devLogged: "مسجلة (تطوير)",
      failed: "فشلت",
      date: "الوقت",
      empty: "لا رسائل",
      emptyBody: "ستظهر هنا رسائل التحقق والاستعادة والإشعارات.",
    },
    savedReplies: {
      title: "الردود المحفوظة",
      subtitle: "قوالب جاهزة للردود المتكررة في المحادثات",
      manage: "إدارة الردود المحفوظة",
      name: "اسم القالب",
      namePlaceholder: "مثال: طلب مزيد من التفاصيل",
      content: "نص الرد",
      contentPlaceholder: "اكتب نص الرد كما سيظهر للعميل…",
      add: "إضافة رد",
      edit: "تحرير",
      delete: "حذف",
      save: "حفظ",
      saved: "حُفظ الرد",
      deleted: "حُذف الرد",
      confirmDelete: "سيُحذف هذا الرد نهائيًا ولا يمكن التراجع.",
      useReply: "رد محفوظ",
      insert: "إدراج",
      empty: "لا ردود محفوظة",
      emptyBody: "أنشئ قوالب للردود المتكررة ليستخدمها الفريق بضغطة واحدة.",
    },
  },
  announce: {
    ariaLabel: "إعلان",
    dismiss: "إخفاء الإعلان",
  },
};
