import type { PortalContent } from "./types";

/** Portal translations — English (mirrors ar.ts; parity is tested) */
export const portalEn: PortalContent = {
  auth: {
    loginTitle: "Sign in",
    loginSubtitle: "Enter your credentials to access your account",
    loginButton: "Sign in",
    logout: "Sign out",
    registerTitle: "Create account",
    registerSubtitle: "New client account — staff accounts use invitations",
    registerButton: "Create account",
    registerSuccessTitle: "Account created",
    registerSuccessBody: "We sent a confirmation link to your email. Confirm it to activate the account and start submitting requests.",
    email: "Email",
    password: "Password",
    passwordHint: "8+ characters, letters and numbers",
    currentPassword: "Current password",
    newPassword: "New password",
    confirmPassword: "Confirm password",
    forgotTitle: "Reset your password",
    forgotHint: "Enter your email and we will send a reset link if an account exists.",
    forgotButton: "Send reset link",
    forgotSent: "If the email is registered, a message will arrive within minutes.",
    forgotSentDev: "Dev mode: the link appears below (never in production).",
    resetTitle: "New password",
    resetButton: "Set password",
    resetSuccess: "Password changed — sign in again.",
    verifyTitle: "Email verification",
    verifyOk: "Email confirmed",
    verifyOkBody: "Your account is active. Sign in to start using the client portal.",
    verifyAlready: "Your email was already confirmed",
    verifyInvalid: "Invalid link",
    verifyInvalidBody: "The link expired or was already used. Request a new one from the sign-in page.",
    noAccount: "No account yet?",
    haveAccount: "Already have an account?",
    backHome: "Back to site",
    pendingVerification: "Your email is not confirmed yet",
    pendingVerificationBody: "Confirming your email enables submitting requests and conversations. Check your inbox or resend the link.",
    resendVerification: "Resend confirmation link",
    devOutboxHint: "Email dev mode: messages are logged to the admin outbox without actual sending.",
    errors: {
      invalid: "Invalid input",
      wrongPassword: "Current password is incorrect",
      emailTaken: "Email already used by another account",
      rateLimited: "Too many attempts — wait a moment and retry",
      credentials: "Sign-in failed — check your email and password (or the account is unavailable)",
      locked: "Account temporarily locked after repeated failed sign-ins",
      passwordWeak: "Weak password: 8+ characters with letters and numbers",
      passwordMismatch: "Passwords do not match",
      nameInvalid: "Invalid name",
      emailInvalid: "Invalid email address",
      required: "This field is required",
      generic: "Unexpected error — try again",
    },
  },
  track: {
    title: "Track your card",
    invalid: "Invalid link",
    invalidBody: "Make sure the link matches exactly what was sent to you, or contact us to issue a new one.",
    expired: "Link expired",
    expiredBody: "This tracking link has expired — contact us to issue a new link for your card.",
    revoked: "This link was revoked",
    revokedBody: "An authorized person disabled this tracking link. Your card data is safe and remains reachable through official channels.",
    loginRequired: "Sign-in required",
    loginRequiredBody: "This card's policy allows tracking through an authorized account only.",
    signIn: "Sign in",
    closed: "Card closed",
    closedBody: "New replies cannot be added to a closed card — you can still review the conversation.",
    rateLimited: "Too many attempts — wait a moment and retry",
    cardType: { request: "Project request", inquiry: "Inquiry" },
    refLabel: "Reference",
    status: "Status",
    created: "Created",
    lastUpdate: "Last update",
    timeline: "Status timeline",
    conversation: "Replies",
    noReplies: "No replies yet",
    guestAuthor: "Tracking-link holder",
    ownerAuthor: "Card owner",
    staffAuthor: "so7ob team",
    you: "You",
    replyTitle: "Add a reply",
    replyPlaceholder: "Write your reply…",
    replyDisabledView: "This card allows view-only access via the link",
    replyDisabledLogin: "Replies require an authorized account — sign in to continue",
    replyDisabledClosed: "Replies are closed on this card",
    send: "Send reply",
    sending: "Sending…",
    replySent: "Your reply was sent",
    replyFailed: "Could not send the reply — try again",
    replyDuplicate: "An identical reply was just sent",
    copyLink: "Copy link",
    copied: "Link copied",
    attachments: "Attachments",
    backHome: "Back to home",
    statusLabels: {
      new: "New",
      in_review: "In review",
      awaiting_info: "Awaiting info",
      in_progress: "In progress",
      responded: "Responded",
      closed: "Closed",
      cancelled: "Cancelled",
    },
    openTracking: "Open tracking",
    copyTracking: "Copy link",
    trackingHint: "Keep this link to follow up and reply to your card anytime — works without an account per the access policy.",
    trackingUnavailable: "Could not create a tracking link right now — keep your reference number; a link can be issued later.",
  },
  account: {
    nav: {
      dashboard: "Dashboard",
      requests: "My requests",
      newRequest: "New request",
      inquiries: "Inquiries",
      notifications: "Notifications",
      profile: "Profile",
      security: "Security & sessions",
      logout: "Sign out",
      backSite: "Public site",
    },
    dashboard: {
      title: "Your dashboard",
      welcome: "Welcome",
      welcomeWithName: "Welcome, {name}",
      openRequests: "Open requests",
      awaitingReply: "Awaiting your reply",
      unreadNotifications: "Unread notifications",
      totalRequests: "Total requests",
      openInquiries: "Open inquiries",
      totalInquiries: "Total inquiries",
      recentUpdates: "Latest updates",
      emptyTitle: "No requests yet",
      emptyBody: "Create your first request — discuss an idea or request a quote.",
      createRequest: "Create request",
      viewAll: "View all",
    },
    requests: {
      title: "My requests",
      subtitle: "Track your requests and their conversations",
      create: "New request",
      refCode: "Reference",
      status: "Status",
      service: "Service",
      created: "Created",
      lastActivity: "Last activity",
      empty: "No requests yet",
      emptyBody: "Start by creating a request — it will appear here with its conversation.",
      viewDetails: "View details",
      cancelEdit: "Cancel",
      submitSuccess: "Request submitted",
      submitSuccessBody: "Its reference code is below — the team will reach out soon.",
      claimTitle: "Link a previous request",
      claimBody: "Enter the reference code of a request you submitted before creating this account; we will email a confirmation link to attach it.",
      claimButton: "Send linking link",
      claimSent: "If the request exists, a confirmation message is on its way.",
      claimVerifyTitle: "Link request to your account",
      claimVerifyOk: "Request linked to your account",
      statuses: {
        new: "New",
        in_review: "In review",
        awaiting_info: "Awaiting info",
        in_progress: "In progress",
        responded: "Responded",
        closed: "Closed",
        cancelled: "Cancelled",
      },
      services: {
        web: "Web development",
        mobile: "Mobile apps",
        systems: "Business systems",
        ux: "UX design",
        automation: "Automation & integration",
        maintenance: "Maintenance & support",
        unsure: "Not sure yet",
      },
      draftRestored: "Your previous draft was restored",
      draftSaved: "Draft saved",
      draftCleared: "Draft cleared",
      search: "Search",
      searchPlaceholder: "Search by reference, service or status…",
      noResults: "No results match your search",
      clearSearch: "Clear search",
      awaitingYou: "Awaiting your reply",
      awaitingHours: "{n}h",
      awaitingDays: "{n}d",
    },
    detail: {
      conversation: "Conversation",
      openTracking: "Open follow-up card",
      internalHidden: "Internal team notes never appear here",
      replyPlaceholder: "Write your reply or addition…",
      send: "Send",
      sending: "Sending…",
      attachFile: "Attach file",
      attachments: "Attachments",
      download: "Download",
      history: "History",
      statusTimeline: "Status timeline",
      assignedTo: "Assigned to",
      unassigned: "Unassigned",
      closedNote: "Closure note",
      replySuccess: "Reply sent",
      replyEmpty: "Write the message first",
      fileTooLarge: "File exceeds the allowed size",
      fileTypeInvalid: "File type not allowed",
      you: "You",
      staff: "Team",
      system: "System",
      noMessages: "No messages yet — the team will reply soon",
      requestInfo: "Request details",
      priority: "Priority",
      timeline: "Timeline",
      budget: "Budget",
      currency: "Currency",
      contactPref: "Preferred contact",
      reference: "Reference link",
      print: "Print request",
    },
    inquiries: {
      title: "My inquiries",
      subtitle: "Quick questions answered by the so7ob team in one thread",
      create: "New inquiry",
      refCode: "Reference",
      subject: "Subject",
      category: "Category",
      categories: {
        general: "General",
        services: "Services",
        pricing: "Pricing",
        support: "Support",
        other: "Other",
      },
      status: "Status",
      statuses: {
        new: "New",
        in_review: "In review",
        awaiting_info: "Awaiting info",
        responded: "Responded",
        closed: "Closed",
      },
      all: "View all",
      openShortcut: "Open inquiries",
      messages: "Messages",
      created: "Created",
      lastActivity: "Last activity",
      empty: "No inquiries yet",
      emptyBody: "Ask your quick question here and the team will reply in the same thread.",
      noResults: "No results match your search",
      viewDetails: "View conversation",
      back: "All inquiries",
      notFound: "Inquiry not found or you don't have access to it",
      conversation: "Conversation",
      meta: "Inquiry details",
      assignedTo: "Handled by",
      unassigned: "Not assigned yet",
      you: "You",
      team: "so7ob team",
      system: "System",
      noMessages: "No messages yet",
      statusTimeline: "Status history",
      replyPlaceholder: "Write your reply or follow-up question…",
      send: "Send",
      sending: "Sending…",
      replySuccess: "Reply sent",
      replyEmpty: "Write the message first",
      closedNote: "This inquiry is closed — start a new one if you need further help.",
      formTitle: "New inquiry",
      formIntro: "A quick question? Write it here and the team will reply in a private thread.",
      formSubject: "Subject",
      formSubjectPlaceholder: "e.g. Do you offer monthly maintenance?",
      formCategory: "Category",
      formMessage: "Your question",
      formMessagePlaceholder: "Write your question clearly — details help us answer better.",
      formSubmit: "Send inquiry",
      formCancel: "Cancel",
      createdOk: "Inquiry sent",
      createdOkBody: "Reference below — the team will reply soon.",
      createdOkOpen: "Open conversation",
      attachments: "Attachments",
      download: "Download",
      print: "Print inquiry",
    openTracking: "Open follow-up card",
    },
    notifications: {
      title: "Notifications",
      markRead: "Mark as read",
      markAllRead: "Mark all read",
      empty: "No notifications",
      types: {
        new_request: "New request",
        new_inquiry: "New inquiry",
        request_assigned: "Request assigned",
        reply_received: "New reply",
        info_requested: "Info requested",
        status_changed: "Status changed",
        content_published: "Content published",
        content_schedule: "Publish schedule",
        account: "Account",
      },
    },
    profile: {
      title: "Profile",
      name: "Name",
      phone: "Phone",
      company: "Company",
      language: "Preferred interface language",
      save: "Save changes",
      saved: "Changes saved",
      emailReadonly: "Email cannot be changed here — contact support",
      verified: "Email verified",
      notVerified: "Email not verified",
    },
    security: {
      title: "Security & sessions",
      changePassword: "Change password",
      passwordChanged: "Password changed",
      passwordChangedBody: "All sessions were revoked — sign in again.",
      sessions: "Active sessions",
      currentSession: "This device",
      thisDevice: "This device",
      revoke: "Revoke",
      revokeAll: "Revoke the rest",
      revoked: "Session revoked",
      lastActive: "Last seen",
      created: "Created",
      unknownDevice: "Unknown device",
      noSessions: "No other active sessions",
      relogin: "Sign in again",
    },
  },
  admin: {
    track: {
      section: "Tracking link",
      noLink: "No tracking link for this card",
      stateValid: "Active",
      stateExpired: "Expired",
      stateRevoked: "Revoked",
      expiresAt: "Expires",
      revokedAt: "Revoked at",
      renew: "Renew link",
      renewed: "Link renewed — copy it now and send it to the client (shown once)",
      renewHint: "Renewing issues a new token, voids the previous one — and emails a copy to the card contact (dev mode: outbox)",
      renewEmailedTo: "A copy was emailed to",
      revoke: "Revoke link",
      revokeConfirm: "The link holder will lose access immediately. Continue?",
      revoked: "Tracking link revoked",
      effectivePolicy: "Effective policy for this card",
      policySource: {
        platform_force_login: "Platform-wide force sign-in",
        card_exception: "Exception for this card",
        type_default: "Type default setting",
      },
      mode: {
        login_required: "Sign-in required",
        link_view: "Link tracking — view only",
        link_reply: "Link tracking — view & reply",
        link_view_login_reply: "View via link — reply by account",
      },
      forceLoginActive: "«Force sign-in» is enabled platform-wide and overrides any exception",
    },
    nav: {
      dashboard: "Dashboard",
      users: "Users",
      requests: "Requests",
      inquiries: "Inquiries",
      notifications: "Notifications",
      pages: "Pages",
      media: "Media",
      menus: "Menus",
      settings: "Settings",
      audit: "Audit log",
      outbox: "Email outbox",
      backSite: "Public site",
      logout: "Sign out",
    },
    search: {
      trigger: "Global search",
      placeholder: "Search users, requests, inquiries, pages…",
      quickNav: "Quick navigation",
      results: "Results",
      searching: "Searching…",
      noResults: "No matching results",
      noResultsHint: "Try a different term or a reference code (e.g. S7-)",
      openHint: "Open to view result",
    },
    dashboard: {
      title: "Admin dashboard",
      totalUsers: "Total users",
      activeUsers: "Active accounts",
      pendingUsers: "Pending verification",
      openRequests: "Open requests",
      newRequests: "New requests",
      awaitingInfo: "Awaiting info",
      unansweredRequests: "Unanswered requests",
      openInquiries: "Open inquiries",
      publishedPages: "Published pages",
      draftPages: "Draft pages",
      requestsByStatus: "Requests by status",
      recentActivity: "Recent activity",
      recentRequests: "Recent requests",
      viewAll: "View all",
      noData: "No data yet",
      last7days: "Last 7 days",
      rangeLabel: "Choose time range",
      range7: "7 days",
      range30: "30 days",
      range90: "90 days",
      overdueReplies: "Overdue replies",
      overdueHint: "Awaiting team reply for 24h+",
    },
    users: {
      title: "Users",
      subtitle: "Manage accounts, roles and statuses",
      search: "Search",
      searchPlaceholder: "Name or email…",
      role: "Role",
      status: "Status",
      statusActive: "Active",
      statusPending: "Pending verification",
      statusSuspended: "Suspended",
      createdAt: "Created",
      lastLogin: "Last sign-in",
      requests: "Requests",
      actions: "Actions",
      suspend: "Suspend",
      activate: "Activate",
      changeRole: "Change role",
      invite: "Invite",
      inviteTitle: "Invite a user",
      inviteEmail: "Invitee email",
      inviteRole: "Role to grant",
      inviteSend: "Send invitation",
      inviteSent: "Invitation sent",
      edit: "Edit",
      save: "Save",
      saved: "Saved",
      cancel: "Cancel",
      confirmSuspend: "Suspend this account? Sessions are revoked immediately.",
      confirmActivate: "Reactivate this account?",
      confirmLastAdmin: "Cannot suspend or demote the last active system admin.",
      emailVerified: "Email verified",
      notVerified: "Email not verified",
      never: "Never signed in",
      filterAll: "All",
      userUpdated: "User updated",
      lastAdminError: "Rejected: last active system admin",
      sendReset: "Send password reset",
      resetSent: "Reset link sent",
      viewProfile: "View profile",
      detail: {
        title: "User profile",
        back: "Back to users",
        accountInfo: "Account info",
        totalRequests: "Total requests",
        openRequests: "Open requests",
        userRequests: "User requests",
        activityLog: "Recent activity",
        sessionsCount: "Active sessions",
        noRequests: "No requests from this user yet",
        suspendedAt: "Suspended at",
        lastSeen: "Last seen",
      },
    },
    requests: {
      title: "Requests",
      subtitle: "Track clients, respond and assign work",
      searchPlaceholder: "Reference, email, name, text…",
      filterStatus: "Status",
      filterPriority: "Priority",
      filterService: "Service",
      filterAssignee: "Assignee",
      filterOverdue: "Overdue 24h+",
      filterAll: "All",
      unassigned: "Unassigned",
      assign: "Assign",
      assignTo: "Assign to",
      assignToMe: "Assign to me",
      changeStatus: "Change status",
      reply: "Reply to client",
      internalNote: "Internal note",
      internalNoteHint: "Staff only — never reaches the client",
      archive: "Archive",
      restore: "Restore",
      archived: "Archived",
      clientReply: "Client reply",
      staffReply: "Staff reply",
      client: "Client",
      none: "—",
      lastActivity: "Last activity",
      viewDetails: "Details",
      bulkArchive: "Archive selected",
      selected: "selected",
      priority: "Priority",
      requestType: "Type",
      discussion: "Discussion",
      quote: "Quote",
      statuses: {
        new: "New",
        in_review: "In review",
        awaiting_info: "Awaiting info",
        in_progress: "In progress",
        responded: "Responded",
        closed: "Closed",
        cancelled: "Cancelled",
      },
      priorities: {
        low: "Low",
        normal: "Normal",
        high: "High",
        urgent: "Urgent",
      },
      services: {
        web: "Web",
        mobile: "Mobile",
        systems: "Systems",
        ux: "UX",
        automation: "Automation",
        maintenance: "Maintenance",
        unsure: "Unsure",
      },
      budget: "Budget",
      currency: "Currency",
      timelinePref: "Timeline",
      contactPref: "Contact",
      contact: "Contact",
      reference: "Reference",
      history: "History",
      conversation: "Conversation",
      messages: "messages",
      empty: "No matching requests",
      emptyBody: "Adjust filters or wait for new requests.",
      closeReason: "Close/cancel reason",
      closeReasonPlaceholder: "Reason visible to the client…",
      statusNotePlaceholder: "Note about this status change (optional)…",
      applyStatus: "Apply",
      sentReply: "Reply sent",
      sentNote: "Internal note added",
      clientView: "Preview what the client sees",
      export: "Export CSV",
      exportOk: "CSV ready; download requested",
      exportLimit: "Export exceeds 100,000 rows or 32 MiB. Narrow the filters and try again.",
      exportFailed: "Download could not be prepared. Check your session and permissions, then retry.",
      awaitingTeam: "Awaiting team reply",
      overdueReply: "Reply overdue",
      agingHours: "{n}h",
      agingDays: "{n}d",
      presetSave: "Save filter",
      presetName: "Filter name",
      presetSaved: "Filter saved",
      presetRemoved: "Filter removed",
      presetApply: "Apply saved filter",
      presetDelete: "Delete saved filter",
      print: "Print request",
    },
    inquiries: {
      title: "Inquiries",
      subtitle: "General questions and direct contact",
      subject: "Subject",
      category: "Category",
      categories: {
        general: "General",
        services: "Services",
        pricing: "Pricing",
        support: "Support",
        other: "Other",
      },
      new: "New",
      reply: "Reply",
      assign: "Assign",
      conversation: "Conversation",
      empty: "No inquiries",
      statuses: {
        new: "New",
        in_review: "In review",
        awaiting_info: "Awaiting info",
        responded: "Responded",
        closed: "Closed",
      },
      export: "Export CSV",
      exportOk: "CSV ready; download requested",
      exportLimit: "Export exceeds 100,000 rows or 32 MiB. Narrow the filters and try again.",
      exportFailed: "Download could not be prepared. Check your session and permissions, then retry.",
      archive: "Archive",
      restore: "Restore",
      archived: "Archived",
      bulkArchive: "Archive selected",
      selected: "selected",
      print: "Print inquiry",
    },
    notifications: {
      title: "Notifications",
      subtitle: "Request, inquiry and content updates for the team",
      markRead: "Mark as read",
      markAllRead: "Mark all as read",
      empty: "No notifications",
      types: {
        new_request: "New request",
        new_inquiry: "New inquiry",
        request_assigned: "Request assigned",
        reply_received: "New reply",
        info_requested: "Info requested",
        status_changed: "Status changed",
        content_published: "Content published",
        content_schedule: "Publish schedule",
        account: "Account",
      },
    },
    pages: {
      title: "Pages",
      subtitle: "Site content — edit, publish and version",
      createPage: "New page",
      pageTitle: "Page",
      rowActions: "Actions — {title}",
      slug: "Slug",
      slugHint: "lowercase latin letters, digits and dashes — empty only for home",
      status: "Status",
      order: "Order",
      updated: "Updated",
      edit: "Edit",
      duplicate: "Duplicate",
      archive: "Archive",
      restore: "Restore",
      preview: "Preview",
      published: "Published",
      draft: "Draft",
      inReview: "In review",
      archivedStatus: "Archived",
      visibility: "Visibility",
      visibilityPublic: "Public",
      visibilityAuth: "Signed-in",
      visibilityRole: "Specific roles",
      home: "Home",
      setHome: "Set as home",
      notHome: "Not home",
      newPageTitle: "New page",
      empty: "No pages",
      emptyBody: "Create the first page with “New page”.",
      versions: "Versions",
      scheduledFor: "Scheduled to publish · {time}",
      versionHistory: "Version history",
      restoreVersion: "Restore this version",
      currentVersion: "Current version",
      compare: "Compare",
      editorTouched: "Editor-modified — seed skips it",
      restoreBoth: "Restore both languages",
      restoreThisLocale: "Restore this language",
      versionNotFound: "Version not found for this language",
      slugTaken: "This slug is used by another page",
      slugInvalid: "Invalid slug format",
      homeSlugHint: "The home page is served from the empty slug (/) — it cannot change",
    },
    editor: {
      title: "Page editor",
      saved: "Saved",
      saving: "Saving…",
      saveFailed: "Save failed — retry",
      unsaved: "Unsaved changes",
      publish: "Publish",
      publishDisabled: "Publishing needs its own permission",
      publishedOk: "Page published",
      ar: "Arabic",
      en: "English",
      blocks: "Blocks",
      library: "Library",
      layers: "Layers",
      searchLayers: "Search layers…",
      canvas: "Canvas",
      properties: "Properties",
      addChild: "Add child inside",
      emptyContainer: "Add an element",
      containerFull: "Container is full — max {max} children",
      nodeLimit: "Maximum page node count reached",
      nodeDeleted: "Node deleted — you can undo",
      selectType: "Choose type",
      appearance: "Device-aware appearance",
      deviceBase: "Base",
      inherited: "Inherited from base",
      reset: "Reset",
      presets: "Presets",
      presetScopeNote: "The style applies to this node only",
      iframePreview: "iframe preview",
      previewWidth: "Preview width",
      previewZoom: "Zoom",
      refreshPreview: "Refresh preview",
      previewSavedNote: "The preview shows the last saved draft",
      testMode: "Test mode",
      testModeBanner: "Interaction test mode — submission is simulated, no real requests are sent",
      confirmDeleteTree: "This node and {count} nested nodes will be deleted.",
      pageRoot: "Page",
      maxDepthHint: "Maximum tree depth",
      addBlock: "Add",
      insertHere: "Insert here",
      delete: "Delete",
      duplicate: "Duplicate",
      copyToClipboard: "Copy to clipboard",
      copiedToClipboard: "Copied to clipboard — paste it on any page",
      paste: "Paste",
      pasteFromClipboard: "Paste from clipboard",
      pastedFromClipboard: "Pasted — you can undo",
      clipboardEmpty: "Clipboard is empty — copy an element from any page first",
      clipboardCleared: "Clipboard cleared",
      clearClipboard: "Clear clipboard",
      pasteNotAllowedHere: "This type can't be pasted inside this parent — try a higher level",
      layerDragHandle: "Drag handle",
      dropIntoContainer: "Drop here to place the block inside this container",
      moveIntoOwnChild: "A block can't be moved inside its own children",
      moveNotAllowedHere: "This block type can't be dropped here — the target container doesn't accept it",
      moveUp: "Up",
      moveDown: "Down",
      undo: "Undo",
      redo: "Redo",
      preview: "Preview",
      deviceDesktop: "Desktop",
      deviceTablet: "Tablet",
      deviceMobile: "Mobile",
      quickAdd: "Quick add a block",
      searchBlocks: "Search blocks by name…",
      noBlocks: "No matching blocks",
      selectedBlock: "Selected block",
      inlineEdit: "Edit text inline",
      inlineEditHint: "Double-click to edit the text directly on the canvas",
      inlineEditingBadge: "Inline editing — Enter commits, Esc cancels",
      editorGuide: {
        title: "Editor guide",
        description: "Everything you need to master the page editor — from the first block to a scheduled publish.",
        filterPlaceholder: "Search the guide…",
        noResults: "No matching results — try another keyword",
        openHint: "F1 or ? from anywhere in the editor",
        sections: [
          {
            title: "Editor overview",
            body: [
              "The top bar gathers the draft language, save indicator, undo/redo, preview devices (375/768/1280), versions, templates, scheduling and publish.",
              "The canvas shows content exactly as visitors see it, with the block library and the selected block's properties on its sides (they swap with the language direction).",
            ],
          },
          {
            title: "Library & canvas",
            body: [
              "Add a block by dragging from the library onto the canvas, or via the quick-add palette (Ctrl+/) — everything is fully keyboard accessible.",
              "The layer tree supports drag & drop from every row's grip handle, and moves any block (with its subtree) across containers: drop it on a row to settle before/after it based on drag direction, or on the “drop here” strip under any expanded container's children to append it.",
              "Cross-container moves enforce strict constraints with explicit messages on violation: the page's node limit, max tree depth measured from the new target, each container's children rules, and a block can never be dropped inside its own children — searching temporarily disables dragging.",
              "The layer tree shows the selected block's path (breadcrumbs above the canvas) — containers like sections and rows delete with all their children after confirmation.",
              "Each block's properties live in the side panel; toggle its visibility on mobile, tablet and desktop from the appearance section.",
            ],
          },
          {
            title: "Inline text editing",
            body: [
              "Double-click any heading, paragraph or button-link — or select it and press Enter — to edit the text in place with the same typography and size.",
              "Enter commits the text and keeps the session open for other elements, Esc reverts the field and closes the session, and paste is stripped to plain text.",
            ],
          },
          {
            title: "Cross-page clipboard",
            body: [
              "Copy any block with its subtree (clipboard button on the floating toolbar, layer tree or properties panel) — the snapshot stays in your browser even after you leave the page.",
              "From the «Paste from clipboard» button in the top bar pick one of your latest copies from any page: it is inserted after the selected block or at the end of the page with fresh IDs, keeping device styles and visibility exactly as copied.",
              "The clipboard holds the last 8 items and can be cleared entirely from the bottom of the paste menu — undo (Ctrl+Z) covers pasting like any other action.",
            ],
          },
          {
            title: "Autosave & revisions",
            body: [
              "Every change autosaves two seconds later — the top indicator shows: saved / saving / unsaved / error / conflict.",
              "Each save bumps the revision number; if another user saves first, a conflict dialog shows the difference: keep my changes or load the server version — nothing is silently overwritten.",
              "Ctrl+S saves instantly at any time, and the discard-unpublished-changes button (for published pages) throws away draft experiments and returns literally to the last published version.",
            ],
          },
          {
            title: "Versions & templates",
            body: [
              "Every publish creates a version per language whose content changed — compare and restore any point from the versions dialog (an automatic backup snapshot is taken before restoring).",
              "Apply a ready-made template in one language within seconds, or save your current page as a custom template the team can reuse — built-in templates are protected; custom ones can be renamed and deleted.",
            ],
          },
          {
            title: "Publish & scheduling",
            body: [
              "Publishing is bound to a saved draft revision: nothing different from what you saw on screen is ever published, and you can publish Arabic without English and vice versa.",
              "Schedule publish (the calendar icon) publishes the draft automatically at the chosen time; the schedule binds to the current revision — changing the draft before the due time skips the publish and notifies you, and cancelling is available at any moment.",
            ],
          },
        ],
        shortcutsTitle: "Keyboard shortcuts",
        shortcuts: [
          { keys: "Ctrl+Z", description: "Undo the last operation" },
          { keys: "Ctrl+Shift+Z or Ctrl+Y", description: "Redo" },
          { keys: "Ctrl+S", description: "Save the draft immediately" },
          { keys: "Ctrl+/", description: "Toggle the quick-add palette" },
          { keys: "Enter", description: "Start inline editing on a selected text leaf" },
          { keys: "Escape", description: "Exit inline session / deselect / exit test mode" },
          { keys: "Double-click", description: "Inline text editing on the canvas" },
          { keys: "F1 or ?", description: "Open this guide" },
        ],
      },
      noSelection: "No selection",
      noSelectionBody: "Pick a block on the canvas to edit its properties, or add a new one from the library.",
      confirmDelete: "Delete this block?",
      autosaveOn: "Autosave enabled",
      conflictTitle: "Edit conflict",
      conflictBody: "A newer version was saved by another user — it cannot be overwritten without your decision.",
      conflictComparing: "Fetching server copy for comparison…",
      conflictLocal: "Your local copy",
      conflictServer: "Server copy",
      conflictSame: "identical",
      conflictDiffers: "differs",
      conflictChoice: "You can keep your changes (they will overwrite the server copy) or load the server copy (your unsaved changes will be lost).",
      conflictKeepMine: "Keep my changes",
      conflictLoadServer: "Load server copy",
      leaveTitle: "You have unsaved changes",
      leaveBody: "Leaving now may lose your edits. Save first, or leave without saving.",
      leaveStay: "Stay in editor",
      leaveDiscard: "Leave without saving",
      leaveSaveAndGo: "Save then leave",
      lastSaved: "Last saved",
      lastEditor: "Last editor",
      unpublishedChanges: "Unpublished changes",
      unpublishedHint: "The draft has changes that are not published yet — visitors see the published copy",
      discard: "Discard unpublished changes",
      discardConfirm: "Discard changes",
      discardDesc: "The draft will revert exactly to the last published version and all unpublished changes will be lost. The published version itself is not affected.",
      discarded: "Changes discarded — draft reverted to last published version",
      schedule: "Schedule publish",
      scheduleDesc: "The current draft content will be published automatically at the chosen time — through the same publish core with all its safety checks (validation, versions, redirects, audit).",
      scheduleBindHint: "The schedule is bound to the current draft revision ({rev}). If the draft changes before the due time, the publish is skipped automatically and the scheduler is notified.",
      scheduleWhen: "Publish at",
      scheduleConfirm: "Confirm schedule",
      scheduleCancelSchedule: "Cancel schedule",
      scheduleCancelDesc: "Nothing will be published automatically — the draft stays as is.",
      scheduleSetOk: "Scheduled to publish automatically at {time}",
      scheduleCancelOk: "Schedule cancelled — nothing will be published automatically",
      scheduleInvalidTime: "Enter a valid date & time",
      schedulePastTime: "The time must be in the future",
      scheduleNothingToCancel: "No active schedule",
      scheduleCurrent: "Current schedule",
      scheduledBadge: "Scheduled to publish",
      scheduledShort: "Scheduled",
      emptyPageError: "Cannot publish a completely empty page in both languages",
      archivedError: "Page is archived — unarchive it first",
      settingsDraftOnly: "These settings are saved to the draft and only reach visitors when published",
      publicTitleAr: "Public title (Arabic)",
      publicTitleEn: "Public title (English)",
      adminTitleAr: "Admin name (Arabic) — internal",
      adminTitleEn: "Admin name (English) — internal",
      slugDraftHint: "The new slug applies to visitors when published, with an automatic redirect from the old one",
      restoreScopeHint: "Restoring overwrites the current draft (an automatic backup snapshot is saved first). Choose one language or both.",
      reload: "Reload",
      leaveWarning: "You have unsaved changes — leaving will discard them.",
      backToList: "Back to list",
      seo: "SEO",
      seoTitle: "Search title",
      seoDescription: "Search description",
      pageSettings: "Page settings",
      visibility: "Visibility",
      allowedRoles: "Allowed roles",
      dirtyIndicator: "Unsaved",
      hiddenOnMobile: "Hidden on mobile",
      hiddenOnTablet: "Hidden on tablet",
      hiddenOnDesktop: "Hidden on desktop",
      background: "Background",
      padding: "Vertical padding",
      style: "Style",
      items: "Items",
      addItem: "Add item",
      removeItem: "Remove",
      linkLabel: "Link label",
      linkHref: "Link URL",
      imageAlt: "Alt text",
      imageSrc: "Image source",
      mediaLibrary: "Media library",
      uploadImage: "Upload image",
      templates: "Templates",
      groups: {
        structure: "Page structure",
        home: "Home sections",
        pages: "Page sections",
        generic: "Generic elements",
        layout: "Layout",
      },
    },
    templates: {
      title: "Page templates",
      subtitle: "Apply a ready-made layout to the draft, or save the current content as a reusable template",
      saveAsTemplate: "Save as template",
      saveFromCurrent: "Save current content as a new template",
      saveHint: "Only the current draft locale is saved — repeat from the other language tab if needed",
      formNameAr: "Template name (Arabic)",
      formNameEn: "Template name (English)",
      formDescAr: "Short description (Arabic) — optional",
      formDescEn: "Short description (English) — optional",
      nameRequired: "Enter the template name in Arabic or English",
      savedOk: "New template saved",
      saveFailed: "Couldn't save the template",
      apply: "Apply to draft",
      applyTo: "Apply",
      applyConfirmTitle: "Apply this template to the draft?",
      applyConfirmBody: "The current draft content will be replaced with the template content",
      applyBackupNote: "An automatic backup of the current content is saved to version history before applying — you can restore it anytime",
      applyLocaleNote: "Only the current draft locale is affected — the other language stays untouched",
      appliedOk: "Template applied to the draft",
      builtin: "Built-in",
      custom: "Custom",
      all: "All",
      usageCountOne: "Used once",
      usageCountTwo: "Used twice",
      usageCountFew: "Used {n} times",
      usageCountMany: "Used {n} times",
      createdBy: "Created by: {name}",
      rename: "Rename",
      renameTitle: "Edit template details",
      renameDesc: "Names and description are bilingual — empty fields keep their current values",
      renamedOk: "Template updated",
      renameFailed: "Couldn't update template",
      empty: "No custom templates yet",
      emptyBody: "Save an existing page as a template so your team can reuse it here",
      loadFailed: "Couldn't load templates",
      delete: "Delete template",
      deleteConfirmTitle: "Delete this template?",
      deleteConfirmBody: "Deletion is permanent and doesn't affect pages it was previously applied to",
      deletedOk: "Template deleted",
      builtinReadonly: "Built-in templates can't be deleted",
      missingLocale: "This template has no content for this locale",
      previewLabel: "Wireframe preview of the {name} template structure",
      previewCaption: "Template structure",
      nodesCountOne: "1 element",
      nodesCountTwo: "2 elements",
      nodesCountFew: "{n} elements",
      nodesCountMany: "{n} elements",
      conflict: "The draft changed on your side or someone else's — reload and try again",
    },
    media: {
      title: "Media library",
      subtitle: "Public site images — alt text matters for accessibility",
      upload: "Upload",
      filename: "File",
      alt: "Alt text",
      size: "Size",
      uploaded: "Uploaded",
      actions: "Actions",
      copyUrl: "Copy URL",
      delete: "Delete",
      deleted: "Deleted",
      uploadedOk: "File uploaded",
      empty: "No media yet",
      confirmDelete: "Delete this file? This cannot be undone.",
      search: "Search",
      searchPlaceholder: "Search by filename or alt text…",
      noResults: "No matching media",
      allFolders: "All folders",
      folder: "Folder",
      folderUpload: "Upload folder",
      moveFolder: "Move to folder",
      folderSaved: "Folder updated",
      inUse: "In use",
      unused: "Unused",
      usedWhere: "Where is it used?",
      deleteBlockedTitle: "Cannot delete media that is in use",
      deleteBlockedDesc: "This media is referenced in the places below — remove the usage first, then retry:",
      usagePagePublished: "Published page",
      usagePageDraft: "Page draft",
      usagePageOg: "Social share image (SEO)",
      usageTemplate: "Page template",
      usageArchived: "archived",
      usageFilterLabel: "Filter by usage state",
      usageFilterAll: "All media",
      usageFilterInUse: "In use",
      usageFilterUnused: "Unused",
    },
    menus: {
      title: "Menus",
      subtitle: "Header and footer links and their order",
      header: "Header menu",
      footer: "Footer menu",
      labelAr: "Label (Arabic)",
      labelEn: "Label (English)",
      linkType: "Link type",
      pageLink: "Content page",
      customUrl: "Custom URL",
      enabled: "Enabled",
      add: "Add link",
      save: "Save menu",
      saved: "Menu saved",
      remove: "Remove",
      pagesPlaceholder: "Pick a page…",
    },
    settings: {
      title: "Site settings",
      subtitle: "Official contact data and links — shown in the footer and contact page",
      contact: "Contact details",
      social: "Social links",
      email: "Email",
      phone: "Phone",
      address: "Address",
      github: "GitHub",
      save: "Save settings",
      saved: "Settings saved",
      announcement: "Top announcement",
      announcementSubtitle: "A site-wide banner for all visitors — stays until dismissed in the browser, and returns automatically when updated",
      announcementMessageAr: "Announcement text (Arabic)",
      announcementMessageEn: "Announcement text (English)",
      announcementCtaLabelAr: "Button label (Arabic)",
      announcementCtaLabelEn: "Button label (English)",
      announcementCtaUrl: "Button link (optional)",
      announcementVariant: "Style",
      announcementVariants: {
        info: "Info",
        warning: "Warning",
        success: "Success",
        brand: "Brand",
      },
      announcementEnabled: "Enabled",
      announcementStart: "Start date (optional)",
      announcementEnd: "End date (optional)",
      track: {
        title: "Follow-up link policy",
        subtitle: "Who can view a follow-up card and reply via its link — applies immediately to every upcoming view and reply",
        forceLogin: "Force sign-in for everyone",
        forceLoginHint: "Highest priority: temporarily overrides all link modes and card exceptions — link holders are always asked to sign in. Turn it off to restore the modes chosen below.",
        requestsMode: "Project requests mode",
        inquiriesMode: "Inquiries mode",
        ttl: "Link validity period (days)",
        ttlHint: "From 1 to 3650 days — applies to links created or renewed from now on",
        allowGuestAttachments: "Allow link holders to attach files to their replies",
        allowGuestAttachmentsHint: "When disabled, uploads are rejected server-side even if the mode allows replying",
        modes: {
          login_required: "Sign-in required — view & reply with an account only",
          link_view: "Link is view-only — replies with an account only",
          link_reply: "Link allows view & reply — no account needed",
          link_view_login_reply: "Link is view-only — replies by authorized accounts",
        },
        preview: "Effective behavior right now",
        previewView: "Link holder can view",
        previewReply: "Link holder can reply without an account",
        previewOwnerReply: "Card owner can reply from their account",
        yes: "Allowed",
        no: "Denied",
        priorityNote: "Priority: forced sign-in ← card exception (from its panel) ← type mode here",
        invalidTtl: "Validity must be a whole number between 1 and 3650",
      },
    },
    audit: {
      title: "Audit log",
      subtitle: "Who did what and when — every sensitive operation",
      actor: "Actor",
      action: "Action",
      entity: "Record",
      date: "Time",
      details: "Details",
      empty: "No events",
    },
    outbox: {
      title: "Email outbox",
      subtitle: "Sent or logged emails — dev mode logs without real sending",
      to: "To",
      subject: "Subject",
      status: "Status",
      sent: "Sent",
      devLogged: "Logged (dev)",
      failed: "Failed",
      date: "Time",
      empty: "No messages",
      emptyBody: "Verification, reset and notification emails will appear here.",
    },
    savedReplies: {
      title: "Saved replies",
      subtitle: "Ready templates for frequent conversation replies",
      manage: "Manage saved replies",
      name: "Template name",
      namePlaceholder: "e.g. Request more details",
      content: "Reply text",
      contentPlaceholder: "Write the reply as the client will see it…",
      add: "Add reply",
      edit: "Edit",
      delete: "Delete",
      save: "Save",
      saved: "Reply saved",
      deleted: "Reply deleted",
      confirmDelete: "This reply will be permanently deleted and cannot be restored.",
      useReply: "Saved reply",
      insert: "Insert",
      empty: "No saved replies",
      emptyBody: "Create templates for frequent replies so the team can insert them in one click.",
    },
  },
  announce: {
    ariaLabel: "Announcement",
    dismiss: "Dismiss announcement",
  },
};
