import type { PortalContent } from "./types";

/** Portal translations — English (mirrors ar.ts; parity is tested) */
export const portalEn: PortalContent = {
  auth: {
    loginTitle: "Sign in",
    loginSubtitle: "Enter your credentials to access your account",
    loginButton: "Sign in",
    logout: "Sign out",
    registerTitle: "Create account",
    registerSubtitle: "New client account — staff accounts use invitations",
    registerButton: "Create account",
    registerSuccessTitle: "Account created",
    registerSuccessBody: "We sent a confirmation link to your email. Confirm it to activate the account and start submitting requests.",
    email: "Email",
    password: "Password",
    passwordHint: "8+ characters, letters and numbers",
    currentPassword: "Current password",
    newPassword: "New password",
    confirmPassword: "Confirm password",
    forgotTitle: "Reset your password",
    forgotHint: "Enter your email and we will send a reset link if an account exists.",
    forgotButton: "Send reset link",
    forgotSent: "If the email is registered, a message will arrive within minutes.",
    forgotSentDev: "Dev mode: the link appears below (never in production).",
    resetTitle: "New password",
    resetButton: "Set password",
    resetSuccess: "Password changed — sign in again.",
    verifyTitle: "Email verification",
    verifyOk: "Email confirmed",
    verifyOkBody: "Your account is active. Sign in to start using the client portal.",
    verifyAlready: "Your email was already confirmed",
    verifyInvalid: "Invalid link",
    verifyInvalidBody: "The link expired or was already used. Request a new one from the sign-in page.",
    noAccount: "No account yet?",
    haveAccount: "Already have an account?",
    backHome: "Back to site",
    pendingVerification: "Your email is not confirmed yet",
    pendingVerificationBody: "Confirming your email enables submitting requests and conversations. Check your inbox or resend the link.",
    resendVerification: "Resend confirmation link",
    devOutboxHint: "Email dev mode: messages are logged to the admin outbox without actual sending.",
    errors: {
      invalid: "Invalid input",
      wrongPassword: "Current password is incorrect",
      emailTaken: "Email already used by another account",
      rateLimited: "Too many attempts — wait a moment and retry",
      credentials: "Sign-in failed — check your email and password (or the account is unavailable)",
      locked: "Account temporarily locked after repeated failed sign-ins",
      passwordWeak: "Weak password: 8+ characters with letters and numbers",
      passwordMismatch: "Passwords do not match",
      nameInvalid: "Invalid name",
      emailInvalid: "Invalid email address",
      required: "This field is required",
      generic: "Unexpected error — try again",
    },
  },
  account: {
    nav: {
      dashboard: "Dashboard",
      requests: "My requests",
      newRequest: "New request",
      inquiries: "Inquiries",
      notifications: "Notifications",
      profile: "Profile",
      security: "Security & sessions",
      logout: "Sign out",
      backSite: "Public site",
    },
    dashboard: {
      title: "Your dashboard",
      welcome: "Welcome",
      welcomeWithName: "Welcome, {name}",
      openRequests: "Open requests",
      awaitingReply: "Awaiting your reply",
      unreadNotifications: "Unread notifications",
      totalRequests: "Total requests",
      openInquiries: "Open inquiries",
      totalInquiries: "Total inquiries",
      recentUpdates: "Latest updates",
      emptyTitle: "No requests yet",
      emptyBody: "Create your first request — discuss an idea or request a quote.",
      createRequest: "Create request",
      viewAll: "View all",
    },
    requests: {
      title: "My requests",
      subtitle: "Track your requests and their conversations",
      create: "New request",
      refCode: "Reference",
      status: "Status",
      service: "Service",
      created: "Created",
      lastActivity: "Last activity",
      empty: "No requests yet",
      emptyBody: "Start by creating a request — it will appear here with its conversation.",
      viewDetails: "View details",
      cancelEdit: "Cancel",
      submitSuccess: "Request submitted",
      submitSuccessBody: "Its reference code is below — the team will reach out soon.",
      claimTitle: "Link a previous request",
      claimBody: "Enter the reference code of a request you submitted before creating this account; we will email a confirmation link to attach it.",
      claimButton: "Send linking link",
      claimSent: "If the request exists, a confirmation message is on its way.",
      claimVerifyTitle: "Link request to your account",
      claimVerifyOk: "Request linked to your account",
      statuses: {
        new: "New",
        in_review: "In review",
        awaiting_info: "Awaiting info",
        in_progress: "In progress",
        responded: "Responded",
        closed: "Closed",
        cancelled: "Cancelled",
      },
      services: {
        web: "Web development",
        mobile: "Mobile apps",
        systems: "Business systems",
        ux: "UX design",
        automation: "Automation & integration",
        maintenance: "Maintenance & support",
        unsure: "Not sure yet",
      },
      draftRestored: "Your previous draft was restored",
      draftSaved: "Draft saved",
      draftCleared: "Draft cleared",
      search: "Search",
      searchPlaceholder: "Search by reference, service or status…",
      noResults: "No results match your search",
      clearSearch: "Clear search",
      awaitingYou: "Awaiting your reply",
      awaitingHours: "{n}h",
      awaitingDays: "{n}d",
    },
    detail: {
      conversation: "Conversation",
      internalHidden: "Internal team notes never appear here",
      replyPlaceholder: "Write your reply or addition…",
      send: "Send",
      sending: "Sending…",
      attachFile: "Attach file",
      attachments: "Attachments",
      download: "Download",
      history: "History",
      statusTimeline: "Status timeline",
      assignedTo: "Assigned to",
      unassigned: "Unassigned",
      closedNote: "Closure note",
      replySuccess: "Reply sent",
      replyEmpty: "Write the message first",
      fileTooLarge: "File exceeds the allowed size",
      fileTypeInvalid: "File type not allowed",
      you: "You",
      staff: "Team",
      system: "System",
      noMessages: "No messages yet — the team will reply soon",
      requestInfo: "Request details",
      priority: "Priority",
      timeline: "Timeline",
      budget: "Budget",
      currency: "Currency",
      contactPref: "Preferred contact",
      reference: "Reference link",
      print: "Print request",
    },
    inquiries: {
      title: "My inquiries",
      subtitle: "Quick questions answered by the so7ob team in one thread",
      create: "New inquiry",
      refCode: "Reference",
      subject: "Subject",
      category: "Category",
      categories: {
        general: "General",
        services: "Services",
        pricing: "Pricing",
        support: "Support",
        other: "Other",
      },
      status: "Status",
      statuses: {
        new: "New",
        in_review: "In review",
        awaiting_info: "Awaiting info",
        responded: "Responded",
        closed: "Closed",
      },
      all: "View all",
      openShortcut: "Open inquiries",
      messages: "Messages",
      created: "Created",
      lastActivity: "Last activity",
      empty: "No inquiries yet",
      emptyBody: "Ask your quick question here and the team will reply in the same thread.",
      noResults: "No results match your search",
      viewDetails: "View conversation",
      back: "All inquiries",
      notFound: "Inquiry not found or you don't have access to it",
      conversation: "Conversation",
      meta: "Inquiry details",
      assignedTo: "Handled by",
      unassigned: "Not assigned yet",
      you: "You",
      team: "so7ob team",
      system: "System",
      noMessages: "No messages yet",
      statusTimeline: "Status history",
      replyPlaceholder: "Write your reply or follow-up question…",
      send: "Send",
      sending: "Sending…",
      replySuccess: "Reply sent",
      replyEmpty: "Write the message first",
      closedNote: "This inquiry is closed — start a new one if you need further help.",
      formTitle: "New inquiry",
      formIntro: "A quick question? Write it here and the team will reply in a private thread.",
      formSubject: "Subject",
      formSubjectPlaceholder: "e.g. Do you offer monthly maintenance?",
      formCategory: "Category",
      formMessage: "Your question",
      formMessagePlaceholder: "Write your question clearly — details help us answer better.",
      formSubmit: "Send inquiry",
      formCancel: "Cancel",
      createdOk: "Inquiry sent",
      createdOkBody: "Reference below — the team will reply soon.",
      createdOkOpen: "Open conversation",
      attachments: "Attachments",
      download: "Download",
      print: "Print inquiry",
    },
    notifications: {
      title: "Notifications",
      markRead: "Mark as read",
      markAllRead: "Mark all read",
      empty: "No notifications",
      types: {
        new_request: "New request",
        new_inquiry: "New inquiry",
        request_assigned: "Request assigned",
        reply_received: "New reply",
        info_requested: "Info requested",
        status_changed: "Status changed",
        content_published: "Content published",
        account: "Account",
      },
    },
    profile: {
      title: "Profile",
      name: "Name",
      phone: "Phone",
      company: "Company",
      language: "Preferred interface language",
      save: "Save changes",
      saved: "Changes saved",
      emailReadonly: "Email cannot be changed here — contact support",
      verified: "Email verified",
      notVerified: "Email not verified",
    },
    security: {
      title: "Security & sessions",
      changePassword: "Change password",
      passwordChanged: "Password changed",
      passwordChangedBody: "All sessions were revoked — sign in again.",
      sessions: "Active sessions",
      currentSession: "This device",
      thisDevice: "This device",
      revoke: "Revoke",
      revokeAll: "Revoke the rest",
      revoked: "Session revoked",
      lastActive: "Last seen",
      created: "Created",
      unknownDevice: "Unknown device",
      noSessions: "No other active sessions",
      relogin: "Sign in again",
    },
  },
  admin: {
    nav: {
      dashboard: "Dashboard",
      users: "Users",
      requests: "Requests",
      inquiries: "Inquiries",
      notifications: "Notifications",
      pages: "Pages",
      media: "Media",
      menus: "Menus",
      settings: "Settings",
      audit: "Audit log",
      outbox: "Email outbox",
      backSite: "Public site",
      logout: "Sign out",
    },
    search: {
      trigger: "Global search",
      placeholder: "Search users, requests, inquiries, pages…",
      quickNav: "Quick navigation",
      results: "Results",
      searching: "Searching…",
      noResults: "No matching results",
      noResultsHint: "Try a different term or a reference code (e.g. S7-)",
      openHint: "Open to view result",
    },
    dashboard: {
      title: "Admin dashboard",
      totalUsers: "Total users",
      activeUsers: "Active accounts",
      pendingUsers: "Pending verification",
      openRequests: "Open requests",
      newRequests: "New requests",
      awaitingInfo: "Awaiting info",
      unansweredRequests: "Unanswered requests",
      openInquiries: "Open inquiries",
      publishedPages: "Published pages",
      draftPages: "Draft pages",
      requestsByStatus: "Requests by status",
      recentActivity: "Recent activity",
      recentRequests: "Recent requests",
      viewAll: "View all",
      noData: "No data yet",
      last7days: "Last 7 days",
      rangeLabel: "Choose time range",
      range7: "7 days",
      range30: "30 days",
      range90: "90 days",
      overdueReplies: "Overdue replies",
      overdueHint: "Awaiting team reply for 24h+",
    },
    users: {
      title: "Users",
      subtitle: "Manage accounts, roles and statuses",
      search: "Search",
      searchPlaceholder: "Name or email…",
      role: "Role",
      status: "Status",
      statusActive: "Active",
      statusPending: "Pending verification",
      statusSuspended: "Suspended",
      createdAt: "Created",
      lastLogin: "Last sign-in",
      requests: "Requests",
      actions: "Actions",
      suspend: "Suspend",
      activate: "Activate",
      changeRole: "Change role",
      invite: "Invite",
      inviteTitle: "Invite a user",
      inviteEmail: "Invitee email",
      inviteRole: "Role to grant",
      inviteSend: "Send invitation",
      inviteSent: "Invitation sent",
      edit: "Edit",
      save: "Save",
      saved: "Saved",
      cancel: "Cancel",
      confirmSuspend: "Suspend this account? Sessions are revoked immediately.",
      confirmActivate: "Reactivate this account?",
      confirmLastAdmin: "Cannot suspend or demote the last active system admin.",
      emailVerified: "Email verified",
      notVerified: "Email not verified",
      never: "Never signed in",
      filterAll: "All",
      userUpdated: "User updated",
      lastAdminError: "Rejected: last active system admin",
      sendReset: "Send password reset",
      resetSent: "Reset link sent",
      viewProfile: "View profile",
      detail: {
        title: "User profile",
        back: "Back to users",
        accountInfo: "Account info",
        totalRequests: "Total requests",
        openRequests: "Open requests",
        userRequests: "User requests",
        activityLog: "Recent activity",
        sessionsCount: "Active sessions",
        noRequests: "No requests from this user yet",
        suspendedAt: "Suspended at",
        lastSeen: "Last seen",
      },
    },
    requests: {
      title: "Requests",
      subtitle: "Track clients, respond and assign work",
      searchPlaceholder: "Reference, email, name, text…",
      filterStatus: "Status",
      filterPriority: "Priority",
      filterService: "Service",
      filterAssignee: "Assignee",
      filterOverdue: "Overdue 24h+",
      filterAll: "All",
      unassigned: "Unassigned",
      assign: "Assign",
      assignTo: "Assign to",
      assignToMe: "Assign to me",
      changeStatus: "Change status",
      reply: "Reply to client",
      internalNote: "Internal note",
      internalNoteHint: "Staff only — never reaches the client",
      archive: "Archive",
      restore: "Restore",
      archived: "Archived",
      clientReply: "Client reply",
      staffReply: "Staff reply",
      client: "Client",
      none: "—",
      lastActivity: "Last activity",
      viewDetails: "Details",
      bulkArchive: "Archive selected",
      selected: "selected",
      priority: "Priority",
      requestType: "Type",
      discussion: "Discussion",
      quote: "Quote",
      statuses: {
        new: "New",
        in_review: "In review",
        awaiting_info: "Awaiting info",
        in_progress: "In progress",
        responded: "Responded",
        closed: "Closed",
        cancelled: "Cancelled",
      },
      priorities: {
        low: "Low",
        normal: "Normal",
        high: "High",
        urgent: "Urgent",
      },
      services: {
        web: "Web",
        mobile: "Mobile",
        systems: "Systems",
        ux: "UX",
        automation: "Automation",
        maintenance: "Maintenance",
        unsure: "Unsure",
      },
      budget: "Budget",
      currency: "Currency",
      timelinePref: "Timeline",
      contactPref: "Contact",
      contact: "Contact",
      reference: "Reference",
      history: "History",
      conversation: "Conversation",
      messages: "messages",
      empty: "No matching requests",
      emptyBody: "Adjust filters or wait for new requests.",
      closeReason: "Close/cancel reason",
      closeReasonPlaceholder: "Reason visible to the client…",
      statusNotePlaceholder: "Note about this status change (optional)…",
      applyStatus: "Apply",
      sentReply: "Reply sent",
      sentNote: "Internal note added",
      clientView: "Preview what the client sees",
      export: "Export CSV",
      exportOk: "Requests file exported",
      awaitingTeam: "Awaiting team reply",
      overdueReply: "Reply overdue",
      agingHours: "{n}h",
      agingDays: "{n}d",
      presetSave: "Save filter",
      presetName: "Filter name",
      presetSaved: "Filter saved",
      presetRemoved: "Filter removed",
      presetApply: "Apply saved filter",
      presetDelete: "Delete saved filter",
      print: "Print request",
    },
    inquiries: {
      title: "Inquiries",
      subtitle: "General questions and direct contact",
      subject: "Subject",
      category: "Category",
      categories: {
        general: "General",
        services: "Services",
        pricing: "Pricing",
        support: "Support",
        other: "Other",
      },
      new: "New",
      reply: "Reply",
      assign: "Assign",
      conversation: "Conversation",
      empty: "No inquiries",
      statuses: {
        new: "New",
        in_review: "In review",
        awaiting_info: "Awaiting info",
        responded: "Responded",
        closed: "Closed",
      },
      export: "Export CSV",
      exportOk: "Inquiries file exported",
      archive: "Archive",
      restore: "Restore",
      archived: "Archived",
      bulkArchive: "Archive selected",
      selected: "selected",
      print: "Print inquiry",
    },
    notifications: {
      title: "Notifications",
      subtitle: "Request, inquiry and content updates for the team",
      markRead: "Mark as read",
      markAllRead: "Mark all as read",
      empty: "No notifications",
      types: {
        new_request: "New request",
        new_inquiry: "New inquiry",
        request_assigned: "Request assigned",
        reply_received: "New reply",
        info_requested: "Info requested",
        status_changed: "Status changed",
        content_published: "Content published",
        account: "Account",
      },
    },
    pages: {
      title: "Pages",
      subtitle: "Site content — edit, publish and version",
      createPage: "New page",
      pageTitle: "Page",
      rowActions: "Actions — {title}",
      slug: "Slug",
      slugHint: "lowercase latin letters, digits and dashes — empty only for home",
      status: "Status",
      order: "Order",
      updated: "Updated",
      edit: "Edit",
      duplicate: "Duplicate",
      archive: "Archive",
      restore: "Restore",
      preview: "Preview",
      published: "Published",
      draft: "Draft",
      inReview: "In review",
      archivedStatus: "Archived",
      visibility: "Visibility",
      visibilityPublic: "Public",
      visibilityAuth: "Signed-in",
      visibilityRole: "Specific roles",
      home: "Home",
      setHome: "Set as home",
      notHome: "Not home",
      newPageTitle: "New page",
      empty: "No pages",
      emptyBody: "Create the first page with “New page”.",
      versions: "Versions",
      versionHistory: "Version history",
      restoreVersion: "Restore this version",
      currentVersion: "Current version",
      compare: "Compare",
      editorTouched: "Editor-modified — seed skips it",
    },
    editor: {
      title: "Page editor",
      saved: "Saved",
      saving: "Saving…",
      saveFailed: "Save failed — retry",
      unsaved: "Unsaved changes",
      publish: "Publish",
      publishDisabled: "Publishing needs its own permission",
      publishedOk: "Page published",
      ar: "Arabic",
      en: "English",
      blocks: "Blocks",
      library: "Library",
      canvas: "Canvas",
      properties: "Properties",
      addBlock: "Add",
      insertHere: "Insert here",
      delete: "Delete",
      duplicate: "Duplicate",
      moveUp: "Up",
      moveDown: "Down",
      undo: "Undo",
      redo: "Redo",
      preview: "Preview",
      deviceDesktop: "Desktop",
      deviceTablet: "Tablet",
      deviceMobile: "Mobile",
      quickAdd: "Quick add a block",
      searchBlocks: "Search blocks by name…",
      noBlocks: "No matching blocks",
      selectedBlock: "Selected block",
      noSelection: "No selection",
      noSelectionBody: "Pick a block on the canvas to edit its properties, or add a new one from the library.",
      confirmDelete: "Delete this block?",
      autosaveOn: "Autosave enabled",
      conflictTitle: "Edit conflict",
      conflictBody: "A newer version was saved by another user. Reload to review it before continuing.",
      reload: "Reload",
      leaveWarning: "You have unsaved changes — leaving will discard them.",
      backToList: "Back to list",
      seo: "SEO",
      seoTitle: "Search title",
      seoDescription: "Search description",
      pageSettings: "Page settings",
      visibility: "Visibility",
      allowedRoles: "Allowed roles",
      dirtyIndicator: "Unsaved",
      hiddenOnMobile: "Hidden on mobile",
      hiddenOnTablet: "Hidden on tablet",
      hiddenOnDesktop: "Hidden on desktop",
      background: "Background",
      padding: "Vertical padding",
      style: "Style",
      items: "Items",
      addItem: "Add item",
      removeItem: "Remove",
      linkLabel: "Link label",
      linkHref: "Link URL",
      imageAlt: "Alt text",
      imageSrc: "Image source",
      mediaLibrary: "Media library",
      uploadImage: "Upload image",
      groups: {
        home: "Home sections",
        pages: "Page sections",
        generic: "Generic elements",
        layout: "Layout",
      },
    },
    media: {
      title: "Media library",
      subtitle: "Public site images — alt text matters for accessibility",
      upload: "Upload",
      filename: "File",
      alt: "Alt text",
      size: "Size",
      uploaded: "Uploaded",
      actions: "Actions",
      copyUrl: "Copy URL",
      delete: "Delete",
      deleted: "Deleted",
      uploadedOk: "File uploaded",
      empty: "No media yet",
      confirmDelete: "Delete this file? Links using it will break.",
    },
    menus: {
      title: "Menus",
      subtitle: "Header and footer links and their order",
      header: "Header menu",
      footer: "Footer menu",
      labelAr: "Label (Arabic)",
      labelEn: "Label (English)",
      linkType: "Link type",
      pageLink: "Content page",
      customUrl: "Custom URL",
      enabled: "Enabled",
      add: "Add link",
      save: "Save menu",
      saved: "Menu saved",
      remove: "Remove",
      pagesPlaceholder: "Pick a page…",
    },
    settings: {
      title: "Site settings",
      subtitle: "Official contact data and links — shown in the footer and contact page",
      contact: "Contact details",
      social: "Social links",
      email: "Email",
      phone: "Phone",
      address: "Address",
      github: "GitHub",
      save: "Save settings",
      saved: "Settings saved",
      announcement: "Top announcement",
      announcementSubtitle: "A site-wide banner for all visitors — stays until dismissed in the browser, and returns automatically when updated",
      announcementMessageAr: "Announcement text (Arabic)",
      announcementMessageEn: "Announcement text (English)",
      announcementCtaLabelAr: "Button label (Arabic)",
      announcementCtaLabelEn: "Button label (English)",
      announcementCtaUrl: "Button link (optional)",
      announcementVariant: "Style",
      announcementVariants: {
        info: "Info",
        warning: "Warning",
        success: "Success",
        brand: "Brand",
      },
      announcementEnabled: "Enabled",
      announcementStart: "Start date (optional)",
      announcementEnd: "End date (optional)",
    },
    audit: {
      title: "Audit log",
      subtitle: "Who did what and when — every sensitive operation",
      actor: "Actor",
      action: "Action",
      entity: "Record",
      date: "Time",
      details: "Details",
      empty: "No events",
    },
    outbox: {
      title: "Email outbox",
      subtitle: "Sent or logged emails — dev mode logs without real sending",
      to: "To",
      subject: "Subject",
      status: "Status",
      sent: "Sent",
      devLogged: "Logged (dev)",
      failed: "Failed",
      date: "Time",
      empty: "No messages",
      emptyBody: "Verification, reset and notification emails will appear here.",
    },
    savedReplies: {
      title: "Saved replies",
      subtitle: "Ready templates for frequent conversation replies",
      manage: "Manage saved replies",
      name: "Template name",
      namePlaceholder: "e.g. Request more details",
      content: "Reply text",
      contentPlaceholder: "Write the reply as the client will see it…",
      add: "Add reply",
      edit: "Edit",
      delete: "Delete",
      save: "Save",
      saved: "Reply saved",
      deleted: "Reply deleted",
      confirmDelete: "This reply will be permanently deleted and cannot be restored.",
      useReply: "Saved reply",
      insert: "Insert",
      empty: "No saved replies",
      emptyBody: "Create templates for frequent replies so the team can insert them in one click.",
    },
  },
  announce: {
    ariaLabel: "Announcement",
    dismiss: "Dismiss announcement",
  },
};
